config/routes.rb
# -*- encoding : utf-8 -*-
PopupStorz::Application.routes.draw do
  get "users/show"

  match "/users/update" => "users#update"
  match '/auth/:provider/callback' => 'services#create'
  match '/auth/facebook/callback' => 'services#create'
  match '/auth/twitter/callback' => 'services#create'
  match '/items/search_keyword' => 'items#search_keyword'
  match '/items/search_category/:id' => 'items#search_category'
  match '/notifications/destroy/:id' => 'notifications#destroy'
  match '/members' => 'users#members'
  match '/admin_items' => "admin/items#index"
  match '/admin_gatherings' => "admin/offers#gatherings"
  match '/admin/users/create' => "admin/users#create"
  match '/admin_send_invitations' => "admin/users#send_invitations"
  #  match '/search_members' => 'users#search_members'
  match '/search_gatherings' => 'searches#search_gatherings'
  match '/search_spaces' => 'searches#search_spaces'
  match '/admin_destroy_user/:id' => "admin/users#destroy_user"
  match '/admin_edit_user/:id' => "admin/users#edit"
  match '/admin_users' => "admin/users#index"
  match '/delete_listings' => "admin/items#delete_listings"
  match "/search_via_price_range" => "items#search_via_price_range"
  match "/items/new/:id" => "items#new_comment"
  match "/items/add_comment" => "items#add_comment"
  match "/items/show/:id" => "items#show"
  match "/users/add_comment" => "users#add_comment"
  match "/items/pop_ups" => "items#my_pop_ups"
  match "/home/terms" => "home#terms"
  match "/home/contact" => "home#contact"
  match "/home/feedback" => "home#feedback"
  match "/home/send_feedback" => "home#send_feedback"
  match "/email_settings" => "email_settings#index"
  
  match "/items/payment_charge/:id" => "items#payment_charge"
  match "/home/pay" => "home#pay"
  match "/join_gathering/:id" => "offers#join_gathering"
  match "/join/:id" => "offers#join"
  match "/approve_gathering_request/:id" => "offers#approve_gathering_request"
  match "/decline_gathering_request/:id" => "offers#decline_gathering_request"
  match "/accept_gathering/:id" => "offers#accept"
  match "/reject_gathering/:id" => "offers#decline"
  match "/products/cancelled_payment_request" => "products#cancelled_payment_request", :as  => :cancel_request
  match "products/completed_payment_request" => "products#completed_payment_request", :as => :complete_request
  match "/send_invitation" => "users#send_invitation"
  match "/invitation" => "users#invitations"
  match "/users/callback" => "users#callback"
  match "/users/send_invitation_to_contacts" => "users#send_invitation_to_contacts"
  match "/contacts/failure" => "users#send_invitation_to_contacts"
  
  match "/email_settings/index" => "email_settings#index"
  match "/email_settings/show" => "email_settings#show"
  match "/email_settings/create" => "email_settings#create"
  match "/email_settings/edit" => "email_settings#edit"
  match "/email_settings/update/:id" => "email_settings#update"
  match "/users/deactivate_account" => "users#deactivate_account"
  match "/send_resposne_request" => "offers#send_resposne_request"
  match "/send_gathering_deadline/:id" => "offers#send_gathering_deadline"
  match "/update_gathering_deadline" => "offers#update_gathering_deadline"
  match "/pending_gathering_acceptance" => "offers#pending_gathering_acceptance"
  match "/offers/add_comment" => "offers#add_comment"
  match "/cancel_booking/:id" => "offers#cancel_booking"
  match "/searches/user_rating" => "searches#user_rating"
  
  devise_for :users, :controllers => {:registrations => "registrations"}

  resources :accounts do
    collection do
      get 'verification_selection'
    end
  end

  resources :searches do
    collection do
      get "search_home"
      get "gatherings"
      get "members"
      get "spaces"
      post "search_gatherings"
      post "search_members"
      post "search_spaces"
    end
  end
  
  resources :email_settings do    
  end

  match '/items/set_dates' => "items#set_dates", :as => :set_dates
  match '/items/exchange_price' => "items#exchange_price", :as => :exchange_price

  resources :ratings do
    collection do
      get "rate"
      post "rate"
    end
  end
  
  resources :messages do
    collection do
      get 'inbox'
      get 'compose'
      get 'sent_items'
      get 'trash'      
      get 'delete'
      get 'empty_trash'
      get 'reply'

      post 'do_reply'
      post 'manage'
      post 'send_message'
      post 'contact_me'
      post 'gathering_message'
    end
  end

  match "account/:id/dashboard" => "accounts#dashboard",  :as  => :dashboard
  match "accept_invitation/:id" => "invitations#accept_invitation",  :as  => :accept_invitation
  match '/sign_out' => 'devise/sessions#destroy'

  devise_for :users do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  get "home/index"
  get "home/about"
  get "items/new"
  
  namespace :admin do
    resources :items do
      collection do
        get :change_recommendation
        post :transfer_ownership
        post :change_commission_rate
        get :change_rate
        post :change_all
        post :display_on_home
        get :active_inactive
        get :offer_activation
      end      
    end
    resources :users do
      collection do
        get :delete_message
        get :all_messages
        post :all_messages
        get :all_feedbacks
        post :all_feedbacks
        get :all_ratings
        get :delete_rating
        get :delete_comment
        #        get :send_invitation
        get :invitations
        post :send_invitation_to_users
        post :send_invitations
        post :send_invitation
        get :all_payments
        get :cancel_payment
#        get :all_feedbacks        
      end
    end
    resources :offers do
      collection do
        post :change_commission_rate
        post :add_comment
      end
    end
    resources :messages do
      collection do
        get :send_to_all
        post :send_message_to_all
        post :send_message_to_user
        get :send_message
      end
    end
  end
  resources :services do
    get "/services/create/:id" => "services#create"
  end
  resources :invitations do
    collection do
      get :fetch
      post :fetch
      post :send_emails
    end
  end

  namespace :xml do
    match 'location_search.xml' => 'LocationSearch#index', :format => :xml
    match 'address_search.xml'  => 'AddressSearch#index' , :format => :xml
  end

  resources :ratings do
    collection do
      get "rate"
      post "rate"
    end
  end
  resources :offers
  resources :avatars
  resources :items do
    collection do
      get "overview"
      get "created_prev_gatherings"
      get "created_coming_gatherings"
      get "pending_gathering_acceptance"
      get "gatherings_at_my_place"
      get "listings_home"
      get "past_transactions"
      get "search_item_spaces"
    end
    resources :avatars
    collection do
      get "sent_requests"      
    end
    get :autocomplete_item_title, :on => :collection
    get :autocomplete_item_city, :on => :collection
    get :add_to_favorite, :on => :member
    get :remove_from_favorite, :on => :member
    get :remove_from_favorite_on, :on => :member
    get :favorites, :on => :collection
    resources :offers do
      resources :payments
      member do
        get 'decline'
        get 'accept'
      end
    end
  end
  
  match '/users/:id/profile' => 'users#show', :as => :profile
  match '/users/:id/profile/edit' => 'users#edit', :as => :edit_profile
  match 'admin/users/:id/profile' => 'admin/users#show', :as => :admin_profile
  root :to => "home#index"
end

app/controllers/admin/messages_controller.rb
class Admin::MessagesController < ApplicationController
  layout "admin"
  def send_to_all
  
  end

  def send_message_to_all
    @users= User.all
    @users.each do |user|
      
      current_user.send_message(user, :topic => "from admin",:body => params[:body].html_safe)

    end
    flash[:alert]= "Your message has been sent to all users!"
    redirect_to admin_items_path
  end

  def send_message
    @user = User.find_by_id(params[:user_id])
  end

  def send_message_to_user
    @user = User.find_by_id(params[:user_id])
    current_user.send_message(@user, :topic => "from admin",:body => params[:body].html_safe)
    flash[:alert]= "Your message has been sent!"
    redirect_to admin_users_path
  end
  
end

app/controllers/messages_controller.rb
# -*- encoding : utf-8 -*-
class MessagesController < ApplicationController  

  def inbox
    @messages = current_user.received_messages.all(:order => "created_at DESC")
    @messages = @messages.paginate(:page => params[:page], :per_page => 10)
  end

  def empty_trash
    current_user.deleted_messages.process do |message|
      message.delete
    end
    flash[:notice] = t(:trash_empty)
    redirect_to trash_messages_path
  end

  def show
    @message = ActsAsMessageable::Message.find_by_id(params[:id])
    @message.mark_as_read
    @message.from.popup_storz_display_name
  end

  def download_attachment
    file_info = Attachment.find params[:id]
    send_file( file_info.attachment.path ,:type => file_info.attachment_content_type)
  end

  def contact_me
    user = User.find_by_id(params[:user_id])
    msg = current_user.send_message(user, :topic => params[:topic], :body => params[:body].html_safe)
    
    respond_to do |format|
      new_msg = ActsAsMessageable::Message.find_by_id(msg.id)
      unless params[:item_id].blank?
        new_msg.update_attribute(:item_id,params[:item_id])
      end
      format.js do
        unless params[:div_id].blank?
          render :js => "alert(#{t(:message_sent)});$('#contact_me_div_#{params[:div_id]}').toggle('slow');$('#body').val('');"
        else
          render :js => "alert(#{t(:message_sent)});$('#contact_me_div').toggle('slow');$('#body').val('');"
        end        
      end
    end    
  end  
  
  def gathering_message    
    user = User.find_by_id(params[:user_id])
    msg = current_user.send_message(user, :topic => params[:topic], :body => params[:body].html_safe)
    respond_to do |format|
      new_msg = ActsAsMessageable::Message.find_by_id(msg.id)
      new_msg.update_attribute(:item_id,params[:item_id])
      format.js do
        render :js => "alert(#{t(:message_sent_to_owner)});$('#contact_me_div').toggle('slow');$('#body').val('');"
      end
    end    
  end
  
  def trash
    @messages = current_user.deleted_messages
    @messages = @messages.paginate(:page => params[:page], :per_page => 6, :order => "created_at DESC" )
  end

  def reply
    @message = ActsAsMessageable::Message.find_by_id(params[:id])
    @message.mark_as_read
  end

  def do_reply
    @message = ActsAsMessageable::Message.find_by_id(params[:message_id])
    @message.reply(:topic => params[:topic], :body => params[:body])
    flash[:notice] = t(:message_sent)
    redirect_to inbox_messages_path
  end

  def manage
    @messages = ActsAsMessageable::Message.all :conditions => ["id IN (?)", params[:message]]    
    case params[:action_to_perform]
    when "mark_as_read"
      @messages.each do |message|
        message.mark_as_read
      end
      flash[:notice] = t(:marked_read)
      redirect_to :action => "inbox"
    when "mark_as_unread"
      @messages.each do |message|
        message.mark_as_unread
      end
      flash[:notice] = t(:marked_unread)
      redirect_to :action => "inbox"
    when "move_to_trash"
      @messages.each do |message|
        current_user.delete_message(message)
      end
      flash[:notice] = t(:message_moved)
      redirect_to inbox_messages_path
    when "move_to_inbox"
      @messages.each do |message|
        message.update_attributes(:sender_delete => false, :recipient_delete => false)
      end
      flash[:notice] = t(:message_moved)
      redirect_to :action => "inbox"
    end
  end

  def move_single_conversation_to_trash
    convo = Conversation.find params[:id]
    current_user.mailbox.move_to(:trash, :conversation => convo)
    flash[:notice] = t(:moved_to_trash)
    redirect_to :action => "inbox"
  end

  def compose    
  end

  def send_message    
    recipients = params[:to].split(/;|,/)
    users = User.all :conditions => ["email in(?)", recipients]
    unless users.blank?
      users.each do |user|
        current_user.send_message(user, :topic => params[:topic], :body => params[:body].html_safe,:item_id => params[:item_id])
      end
      flash[:notice] = t(:message_sent)
      redirect_to inbox_messages_path
    else
      flash[:notice] = t(:provide_correct_email)
      render :action => "compose"
    end    
  end

  def sent_items
    @messages = current_user.sent_messages
    @messages = @messages.paginate(:page => params[:page], :per_page => 6, :order => "created_at DESC" )
  end

  def reply_to_conversation
    @attachments = []
    if current_user.tmps.size > 0
      current_user.tmps.each do |tmp|
        @attachments << File.open( "#{RAILS_ROOT}/#{tmp.path}" )
      end
    end
    recipients = params[:to].split(/;|,/)
    users = User.all :conditions => ["login in(?) OR email in(?)", recipients, recipients]
    body =    params[:message][:body].nil?    ? "" : params[:message][:body]
    subject = params[:message][:subject].nil? ? "" : params[:message][:subject]
    @mail = current_user.reply(Conversation.find(params[:id]), users , body, subject,@attachments)
    cleanup(@attachments)
    flash[:notice] = t(:reply_sent)
    redirect_to :controller => "message_system", :action => "inbox"
  end

  def reply_all_to_conversation
    @attachments = []
    current_user.tmps.each do |tmp|
      @attachments << File.open( "#{RAILS_ROOT}/#{tmp.path}" )
    end
    mail = Mail.find params[:id]
    body =    params[:message][:body].nil?    ? "" : params[:message][:body]
    subject = params[:message][:subject].nil? ? "" : params[:message][:subject]
    current_user.reply_to_all(mail, body, subject,@attachments)
    cleanup(@attachments)
    flash[:notice] = t(:reply_sent_to_all)
    redirect_to :controller => "message_system", :action => "inbox"
  end

  def reply_mail
    @action_url = "reply_to_conversation"
    @from = "Reply"
    @org_message = Message.find params[:message_id]
    @conversation_or_mail_id = params[:id]
    subject = @org_message.subject.sub(/^(Re: )?/, "Re: ")
    body = "#{@org_message.sender.login} wrote on #{@org_message.created_at.strftime('%A %B %d %I:%M:%S %p %Y')}: \n> " + @org_message.body
    @message = Message.new(:sender_id => params[:sender_id], :subject => subject, :body => body)
    @reply_setter = params[:reply_setter]
    render :template => "message_system/compose"
  end

  def reply_all_to_mail
    @action_url = "reply_all_to_conversation"
    @from = "Reply_all"
    @org_message = Message.find params[:message_id]
    @mail = Mail.find params[:id]
    @conversation_or_mail_id = params[:id]
    subject = @org_message.subject.sub(/^(Re: )?/, "Re: ")
    @recipients_for_reply_all = [ [@org_message.sender.login] + @org_message.recipients.map { |recipient| recipient.login } - [ current_user.login] ].join(";")
    body = "#{@org_message.sender.login} wrote on #{@org_message.created_at.strftime('%A %B %d %I:%M:%S %p %Y')}: \n> " + @org_message.body
    @message = Message.new(:subject => subject, :body => body)
    render :template => "message_system/compose"
  end
end

app/helpers/admin/messages_helper.rb
module Admin::MessagesHelper
end

app/helpers/messages_helper.rb
# -*- encoding : utf-8 -*-
module MessagesHelper
end

app/views/messages/_add_attachment.html.erb
<div style="float:left;margin-bottom:10px;height:auto;width: 100%;">
  <%= file_field_tag "attachment[]" , :class => "files"%>
  <a href="#" onclick="removeNodes('<%= params[:div_id] %>');return false;"><%= t(:delete) %></a>
</div>

app/views/messages/_message_header.html.erb
<div class="submenu"> <!-- style="float: left; height: 500px; width: 250px;margin-top: 10px;" -->
  <%#= link_to "Compose", compose_messages_path, 
  :class => "#{params[:action] == 'compose' ? 'selected' : 'unselected'}" %>
  
  <%= link_to "Received", inbox_messages_path, 
  :style => "padding-right: 0;",
  :class => "#{params[:action] == 'inbox' ? 'selected' : 'unselected'}" %>
  <span style="padding-right: 20px;" class="<%= "#{params[:action] == 'inbox' ? 'selected' : 'unselected'}" %>" >(<%= current_user.messages.are_to(current_user).unread.size %>)</span><span class="separator"></span>
  
  <%= link_to "Sent" , sent_items_messages_path, 
  :class => "#{params[:action] == 'sent_items' ? 'selected' : 'unselected'}" %><span class="separator"></span>
  
  <%= link_to "Trash", trash_messages_path, 
  :class => "#{params[:action] == 'trash' ? 'selected' : 'unselected'}" %>
</div>

app/views/messages/_messages.html.erb
<% unless @messages.blank? %>
  <%= form_tag manage_messages_path, :name => "message_form" do %>

    <div style="float: right;line-height: 20px; margin-bottom: 20px; font-size: 1.2em;" >
      <% if  params[:action] == "trash" %>
        <%= link_to "Move back to messages",  "#", :style =>  "background: none repeat scroll 0 0 #00DAFF;", :class => "action", :onclick => "checkListOfCheckBox('move_to_inbox');return false;" %>
        <%= link_to "Empty Trash", empty_trash_messages_path ,:class => "action", :confirm => "Are you sure you want to delete all messages?" %>
      <%else%>
        <% unless @messages.blank? %>
          <%= link_to "Delete",  "#",:class => "action", :onclick => "checkListOfCheckBox('move_to_trash'); return false;" %>
          <%= link_to "Mark As Unread",  "#",:class => "action", :onclick => "checkListOfCheckBox('mark_as_unread'); return false;" %>
        <% end %>
      <%end%>
      <%= will_paginate(@messages, :params => params, :renderer => PaginationListLinkRenderer) %>    
    </div>

    <div class="clear" ></div>
    <%= hidden_field_tag "action_to_perform" , "", :class => "action_to_perform"  %>
    <% @messages.each do |message| %>
      <div class="<%= message.opened == true ? 'mail-list-hover row' : 'mail-list-hover row unread' %>">

        <span class="checkbox" style="float:left;width:20px;margin-top:9px;" >
          <%=  check_box_tag "message[]", message.id, false, {:id => "messages_#{message.id}", :class => "checkBoxClass"} %>
        </span>
        <div style="" onclick="window.location='<%= "/messages/reply?id=#{message.id}" %>'">
          <span style="width:130px;float:left;margin-left:5px;padding-top:2px;">
            <%=  message.from.popup_storz_display_name %>
          </span>
          <span style="float:left;padding-top:2px;">
            <span style="color:grey;float: left;width: 200px">
            <%=  message.topic %> -
            </span>
            <span style="color:grey;float: left;width: 475px;">
              <%=  raw message.body[0...35].gsub("<a href=",'') + '...'%>
            </span>
          </span>
          <span style="width:125px;float:right;padding-top:2px;">
            <%=  message.created_at.strftime("%b. %d, %Y") %>
          </span>
        </div>
      </div>
    <%end%>
  <%end%>

  <script type="text/javascript">
    function checkListOfCheckBox(action){
      elementArray = document.getElementsByName('message[]')
      var check_boxes_length = elementArray.length;
      var breaked = false;
      for(var count = 0 ; count < check_boxes_length ; count++){
        if(elementArray[count].checked == true){
          breaked = true;
          break;
        }
      }
      if(breaked == true){
        $('#action_to_perform').val(action);
        document.message_form.submit();
        return true;
      }
      else{
        alert('No Mail selected.');
        return false;
      }
    }
	  
    $(document).ready(function(){
      $("#check_all").click(function(){
        var checked_status = this.checked;
        $(".checkBoxClass").each(function(){
          this.checked = checked_status;
        });
      });
    });
  </script>

<%else%>
  <div class="clear" ></div>
  <div class="row" style="cursor: not-allowed;"><%= t(:no_msg) %></div>
<%end%>

app/views/messages/inbox.html.erb
<div id="message_detail_div" class="shadowCont message">
  <%= render "message_header" %>
  <%= render :partial => "messages", :locals => {:messages => @messages } %>
</div>

app/views/messages/mail_details.html.erb
<% if session[:from] and session[:from] == "inbox" %>
  <%= link_to "#{t(:back_inbox)}", :controller => "message_system", :action => "inbox" %>&nbsp;&nbsp;&nbsp;
  <%= link_to "#{t(:delete)}", :controller => "message_system", :action => "move_single_conversation_to_trash" , :id => @conversation_details.first.conversation_id %>
<% end %>
<% if session[:from] and session[:from] == "sent" %>
  <%= link_to "#{t(:back_sent)}", :controller => "message_system", :action => "sent" %>&nbsp;&nbsp;&nbsp;
  <%= link_to "#{t(:delete)}", :controller => "message_system", :action => "move_single_conversation_to_trash" , :id => @conversation_details.first.conversation_id %>
<% end %>
<% if session[:from] and session[:from] == "trash" %>
  <%= link_to "#{t(:back_trash)}", :controller => "message_system", :action => "trash" %>&nbsp;&nbsp;&nbsp;
<% end %>



<% @conversation_details.each do |mail| %>
  <div style="margin-left: 5px;border: 1px solid #cccccc; padding-top: 10px;height: auto;overflow: hidden; margin-top: 13px;">
    <div style="width:auto;float:left;font-size: 18px;font-weight: bold; margin: 0px 10px;">
      <%= mail.message.subject %>
    </div>


    <div style="width:100%;float:left;margin-top: 10px; background: #efefef; padding: 7px; padding-bottom: 0px;color: #009900;">
      <div style="float:right;margin-right: 15px;margin-bottom: 5px;">
        <%= mail.message.created_at.strftime("%d %b %y") %> (<%= time_ago_in_words(mail.message.created_at) %> <%= t( :ago ) %>)
      </div>
      <span style="color:#606060;width: 32px;float:left;">
        <%= t(:from) %>
      </span>
      <b>
        <%= mail.message.sender.login %>
      </b>
    </div>

    <div style="width:100%;float:left;margin-bottom: 10px;background: #efefef; padding: 7px; padding-top: 3px; color: #009900;">
      <span style="color:#606060;width: 32px;float:left;">
        <%= t(:to) %>
      </span>
      <b>
        <% mail.message.recipients.each do |recipient|%>
          <%= recipient.login %> &nbsp;
        <%end%>
      </b>
    </div>

    <div style="width:100%; float: left; height: auto; overflow: hidden;">
      
      <div style="width:auto; float:left; padding: 10px; padding-top: 0px;"><%= simple_format(mail.message.body) %></div>

    </div>

    <% if find_conversation_have_attachment?(mail) %>
      <div style="width:100%; height: 1px; float: left; overflow: hidden; border-top: 1px solid #efefef; margin: 10px 0px;"></div>
      <div style="width:100%; float: left;">
        <div style="width:auto; float: left;  padding: 0px 8px;">
          <%= t(:download_attachments) %>:
        </div>
        <div style="width:auto; float: left;  padding: 0px 10px;">
          <% mail.message.attachments.each do |attached_file| %>
            <%= link_to attached_file.attachment_file_name , { :controller => "message_system", :action => "download_attachment", :id => attached_file.id }%> &nbsp;&nbsp;
          <%end%>
        </div>
      </div>
    <% else %>
      <div style="width:100%; height: 1px; float: left; overflow: hidden; border-top: 1px solid #efefef; margin: 10px 0px;"></div>
    <% end %>

    <div style="float:left;width:100%; background: #efefef; padding: 8px 5px; margin-top: 10px; ">
      <%= link_to "#{t(:reply)}" , :controller =>"message_system", :action => "reply_mail", :id => mail.conversation_id, :sender_id => mail.message.sender_id, :message_id => mail.message.id , :reply_setter => params[:reply_setter] %>&nbsp; | &nbsp;
      <%= link_to "#{t(:reply_all)}" , :controller =>"message_system", :action => "reply_all_to_mail", :id => mail.id,  :message_id => mail.message.id , :reply_setter => params[:reply_setter]%>
    </div>
  </div>

<%end%>

app/views/messages/message_details.html.erb
<br/><br/>

<%= t(:msg_detail) %>

<br/>


<br/>



  <%= t(:sender) %> <%= @mail.message.sender.login %>
  <br/>
  <%= t(:recipients) %> &nbsp;
  <% @mail.message.recipients.each do |recipient|%>
      <%= recipient.login %> &nbsp;
  <%end%>


  <br/>
  <%= t(:tittel) %><%= @mail.message.subject %>
  <br/>
  <%= t(:melding) %><%= @mail.message.body %>
  <br/>
  <br/>

app/views/messages/reply.html.erb
<div id="message_detail_div" class="shadowCont message">

  <div class="myTableMenu" align="center" style="cursor: pointer; margin-bottom: 10px; text-align: left;"  onclick="window.location='<%= inbox_messages_path %>'">
    <a><span><div>&lt; Back to messages</div></span></a>
  </div>

  <div style="color: #CC33CC; position: absolute; text-align: center; width: 65%; line-height: 20px; font-size: 1.3em;" >
    TODO Title Offer...
  </div>
  <div class="submenu"> <!-- style="float: left; height: 500px; width: 250px;margin-top: 10px;" -->
    <%= @message.topic %>
  </div>

  <div style="float: right;line-height: 20px; margin-bottom: 10px; font-size: 1.2em;"> 
    <%= link_to "Mark as unread", manage_messages_path(:message => [@message.id], :action_to_perform => "mark_as_unread"), :method => :post, :style=>"background: none repeat scroll 0 0 #00DAFF;", :class=>"action" %>
  </div>
  <div class="clear" ></div>

  <% conversations = @message.conversation.sort_by{|e| e[:id]} %>
  <% conversations.each do|conv| %>
    <div style="margin-bottom: 10px;">
      <div style="height: 0px; border-bottom: 1px solid grey;margin-bottom: 10px;"></div>
      <%= conv.from == current_user ? "Me": conv.from.popup_storz_display_name; %><span style="float: right;"><%= conv.created_at.strftime("%d %b %y") %></span>
      <div class="clear" ></div>
      <div class="body"><%= raw (nl2br(conv.body)) %></div>
    </div>
  <% end %>
  <%= form_tag  do_reply_messages_path, { :id => "email_compose_form" } do %>
    <%= hidden_field_tag :message_id , @message.id %>

    <!--div style="width:100%;float:left;height:50px;margin-top: 10px;">
      <div style="width: 75px;float:left;margin-top: 7px;">
    <%= t(:sub_mail) %>&nbsp;&nbsp;&nbsp;
      </div>
      <div style="width: 500px;float:left;">
    <%= text_field_tag :topic,"Re: #{@message.topic}"  , :style => "width:520px;"%>
      </div>
    </div-->

    <div style="width:100%;">
      <%= text_area_tag :body, "", :style => "width:98%;height:65px;", :hint => "Write message here..." %>
    </div>

    <div>
      <div class="myTableMenu" align="center" style="float:left;cursor: pointer;margin-top: 10px;"  onclick="checkFields();">
        <a><span><div class="search">Send</div></span></a>
      </div>

    </div>
  <% end %>
</div>

<script type="text/javascript">
  function checkFields(){
    if($('#topic').val() == ""){
      alert('Please enter subject.');
      return false;
    }else if($('#body').val() == ""){
      alert('Please enter body.');
      return false;
    }
    else{
      $('#email_compose_form').submit();
    }
  }
</script>

app/views/messages/show.html.erb
<div id="message_detail_div" class="shadowCont message">
	<%= render "message_header" %>
	<div style="float: right;line-height: 20px; margin-bottom: 20px;"> 
		<%= link_to "Mark as unread", manage_messages_path(:message => [@message.id], :action_to_perform => "mark_as_unread"), :method => :post, :class=>"action" %>
      <%= link_to "Reply", reply_messages_path(:id => @message.id), :class=>"action" %>
   </div>
   <div class="clear" ></div>
	<div style="border: 1px solid #999999; padding: 20px;">
		<%= @message.topic %>
	  <%= @message.from.popup_storz_display_name %><span style="float: right;" ><%=  @message.created_at.strftime("%d %b %Y") %></span>
	  Body: <%=  raw (nl2br(@message.body)) %>
	  <br/>
	  <br/>
	  Date: 
	</div>
</div>