config/routes.rb
# -*- encoding : utf-8 -*-
PopupStorz::Application.routes.draw do
  get "users/show"

  match "/users/update" => "users#update"
  match '/auth/:provider/callback' => 'services#create'
  match '/auth/facebook/callback' => 'services#create'
  match '/auth/twitter/callback' => 'services#create'
  match '/items/search_keyword' => 'items#search_keyword'
  match '/items/search_category/:id' => 'items#search_category'
  match '/notifications/destroy/:id' => 'notifications#destroy'
  match '/members' => 'users#members'
  match '/admin_items' => "admin/items#index"
  match '/admin_gatherings' => "admin/offers#gatherings"
  match '/admin/users/create' => "admin/users#create"
  match '/admin_send_invitations' => "admin/users#send_invitations"
  #  match '/search_members' => 'users#search_members'
  match '/search_gatherings' => 'searches#search_gatherings'
  match '/search_spaces' => 'searches#search_spaces'
  match '/admin_destroy_user/:id' => "admin/users#destroy_user"
  match '/admin_edit_user/:id' => "admin/users#edit"
  match '/admin_users' => "admin/users#index"
  match '/delete_listings' => "admin/items#delete_listings"
  match "/search_via_price_range" => "items#search_via_price_range"
  match "/items/new/:id" => "items#new_comment"
  match "/items/add_comment" => "items#add_comment"
  match "/items/show/:id" => "items#show"
  match "/users/add_comment" => "users#add_comment"
  match "/items/pop_ups" => "items#my_pop_ups"
  match "/home/terms" => "home#terms"
  match "/home/contact" => "home#contact"
  match "/home/feedback" => "home#feedback"
  match "/home/send_feedback" => "home#send_feedback"
  match "/email_settings" => "email_settings#index"
  
  match "/items/payment_charge/:id" => "items#payment_charge"
  match "/home/pay" => "home#pay"
  match "/join_gathering/:id" => "offers#join_gathering"
  match "/join/:id" => "offers#join"
  match "/approve_gathering_request/:id" => "offers#approve_gathering_request"
  match "/decline_gathering_request/:id" => "offers#decline_gathering_request"
  match "/accept_gathering/:id" => "offers#accept"
  match "/reject_gathering/:id" => "offers#decline"
  match "/products/cancelled_payment_request" => "products#cancelled_payment_request", :as  => :cancel_request
  match "products/completed_payment_request" => "products#completed_payment_request", :as => :complete_request
  match "/send_invitation" => "users#send_invitation"
  match "/invitation" => "users#invitations"
  match "/users/callback" => "users#callback"
  match "/users/send_invitation_to_contacts" => "users#send_invitation_to_contacts"
  match "/contacts/failure" => "users#send_invitation_to_contacts"
  
  match "/email_settings/index" => "email_settings#index"
  match "/email_settings/show" => "email_settings#show"
  match "/email_settings/create" => "email_settings#create"
  match "/email_settings/edit" => "email_settings#edit"
  match "/email_settings/update/:id" => "email_settings#update"
  match "/users/deactivate_account" => "users#deactivate_account"
  match "/send_resposne_request" => "offers#send_resposne_request"
  match "/send_gathering_deadline/:id" => "offers#send_gathering_deadline"
  match "/update_gathering_deadline" => "offers#update_gathering_deadline"
  match "/pending_gathering_acceptance" => "offers#pending_gathering_acceptance"
  match "/offers/add_comment" => "offers#add_comment"
  match "/cancel_booking/:id" => "offers#cancel_booking"
  match "/searches/user_rating" => "searches#user_rating"
  
  devise_for :users, :controllers => {:registrations => "registrations"}

  resources :accounts do
    collection do
      get 'verification_selection'
    end
  end

  resources :searches do
    collection do
      get "search_home"
      get "gatherings"
      get "members"
      get "spaces"
      post "search_gatherings"
      post "search_members"
      post "search_spaces"
    end
  end
  
  resources :email_settings do    
  end

  match '/items/set_dates' => "items#set_dates", :as => :set_dates
  match '/items/exchange_price' => "items#exchange_price", :as => :exchange_price

  resources :ratings do
    collection do
      get "rate"
      post "rate"
    end
  end
  
  resources :messages do
    collection do
      get 'inbox'
      get 'compose'
      get 'sent_items'
      get 'trash'      
      get 'delete'
      get 'empty_trash'
      get 'reply'

      post 'do_reply'
      post 'manage'
      post 'send_message'
      post 'contact_me'
      post 'gathering_message'
    end
  end

  match "account/:id/dashboard" => "accounts#dashboard",  :as  => :dashboard
  match "accept_invitation/:id" => "invitations#accept_invitation",  :as  => :accept_invitation
  match '/sign_out' => 'devise/sessions#destroy'

  devise_for :users do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  get "home/index"
  get "home/about"
  get "items/new"
  
  namespace :admin do
    resources :items do
      collection do
        get :change_recommendation
        post :transfer_ownership
        post :change_commission_rate
        get :change_rate
        post :change_all
        post :display_on_home
        get :active_inactive
        get :offer_activation
      end      
    end
    resources :users do
      collection do
        get :delete_message
        get :all_messages
        post :all_messages
        get :all_feedbacks
        post :all_feedbacks
        get :all_ratings
        get :delete_rating
        get :delete_comment
        #        get :send_invitation
        get :invitations
        post :send_invitation_to_users
        post :send_invitations
        post :send_invitation
        get :all_payments
        get :cancel_payment
#        get :all_feedbacks        
      end
    end
    resources :offers do
      collection do
        post :change_commission_rate
        post :add_comment
      end
    end
    resources :messages do
      collection do
        get :send_to_all
        post :send_message_to_all
        post :send_message_to_user
        get :send_message
      end
    end
  end
  resources :services do
    get "/services/create/:id" => "services#create"
  end
  resources :invitations do
    collection do
      get :fetch
      post :fetch
      post :send_emails
    end
  end

  namespace :xml do
    match 'location_search.xml' => 'LocationSearch#index', :format => :xml
    match 'address_search.xml'  => 'AddressSearch#index' , :format => :xml
  end

  resources :ratings do
    collection do
      get "rate"
      post "rate"
    end
  end
  resources :offers
  resources :avatars
  resources :items do
    collection do
      get "overview"
      get "created_prev_gatherings"
      get "created_coming_gatherings"
      get "pending_gathering_acceptance"
      get "gatherings_at_my_place"
      get "listings_home"
      get "past_transactions"
      get "search_item_spaces"
    end
    resources :avatars
    collection do
      get "sent_requests"      
    end
    get :autocomplete_item_title, :on => :collection
    get :autocomplete_item_city, :on => :collection
    get :add_to_favorite, :on => :member
    get :remove_from_favorite, :on => :member
    get :remove_from_favorite_on, :on => :member
    get :favorites, :on => :collection
    resources :offers do
      resources :payments
      member do
        get 'decline'
        get 'accept'
      end
    end
  end
  
  match '/users/:id/profile' => 'users#show', :as => :profile
  match '/users/:id/profile/edit' => 'users#edit', :as => :edit_profile
  match 'admin/users/:id/profile' => 'admin/users#show', :as => :admin_profile
  root :to => "home#index"
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  def search_home
  end

  def gatherings
    @sizes = Offer.select("distinct(gathering_rental_price)").where("gathering_rental_price is not NULL").order("gathering_rental_price ASC")
    @start_price = @sizes.first
    @last_price = @sizes.last
    
    @start_price = @start_price.blank? ? 0 : @start_price.gathering_rental_price
    unless @last_price.blank?
      @last_price = @last_price.gathering_rental_price.to_f > 10000 ? @last_price.gathering_rental_price : 10000
    else
      @last_price = 10000
    end
    @users_with_uniq_cities = Item.select("distinct(city)").where("city is not NULL and city != ''")    
    
    count = 1
    items = ""
    
    conds = "status != 'Cancelled' and parent_id is NULL and is_gathering = true and persons_in_gathering > 0"
    sel_items = Item.find(:all)
    sel_items.each do|item|
      if count != 1
        items = items +","+ "#{item.id.to_s}"
      else
        items += item.id.to_s
      end
      count += 1
    end
    unless sel_items.blank?
      conds += " AND item_id in (#{items})"
    end
    
    @gatherings = Offer.find(:all,:conditions => [ conds ], :order=> "rental_start_date ASC")
    unless @gatherings.blank?
      @gatherings = @gatherings.uniq
    end
    gaths = []
    @gatherings.each do|g|
      if g.members.size.to_i < g.persons_in_gathering.to_i
        gaths << g
      end
    end
    @gatherings = gaths
    
    @gatherings = @gatherings.paginate(:page => params[:page], :per_page => 6 )
    respond_to do |format| 
      format.html
      format.js do
        foo = render_to_string(:partial => 'gatherings', :locals => { :offers => @gatherings,:params => params }).to_json
        render :js => "$('#searched-gatherings').html(#{foo});$.setAjaxPagination();"
      end
    end
  end
  
  def search_gatherings
    conds = "status != 'Cancelled' and parent_id is NULL and is_gathering = true and persons_in_gathering > 0 "
    cities = []
    city_conds = "1=1"
    items = ""
    if params[:location] && !params[:location].blank?
      city_conds += " AND (LOWER(city) LIKE " + "'%%" + params[:location].strip.downcase.to_s+ "%%'" +")"
    end
    sel_items = Item.find(:all, :conditions => [ city_conds ])      
    count = 1
    sel_items.each do|item|
      if count != 1
        items = items +","+ "#{item.id.to_s}"
      else
        items += item.id.to_s
      end
      count += 1
    end
        
    unless params[:search_from].blank?
      start_time =  DateTime.strptime(params[:search_from], "%m/%d/%Y").to_date      
      conds += " AND ('#{start_time.to_s}' between rental_start_date and rental_end_date)"
    end
    
    unless params[:search_to].blank?
      end_time =  DateTime.strptime(params[:search_to], "%m/%d/%Y").to_date
      conds += " AND ('#{end_time.to_s}' between rental_start_date and rental_end_date)"
    end
    
    unless params[:min_price].blank?
      conds += " AND (gathering_rental_price >= '#{params[:min_price]}')"
    end
    
    unless params[:max_price].blank?
      conds += " AND (gathering_rental_price <= '#{params[:max_price]}')"
    end
        
    unless sel_items.blank?
      conds += " AND item_id in (#{items})"
    end
    
    case params[:sort_option]
    when "1"
      order_by = "is_recommended, gathering_rental_price DESC"
    when "2"
      order_by = "gathering_rental_price DESC"
    when "3"
      order_by = "gathering_rental_price ASC"
    when "4"
      order_by = "created_at DESC"
    when "5"
      order_by = "created_at ASC"
    else
      order_by = "gathering_rental_price ASC"
    end    
    @gatherings = Offer.find(:all,:conditions => [ conds ], :order=> order_by)    
    unless @gatherings.blank?
      @gatherings = @gatherings.uniq
    end
    
    @min_price = @gatherings.blank? ? 0 : @gatherings.first.gathering_rental_price
    @max_price = @gatherings.blank? ? 0 : @gatherings.last.gathering_rental_price
    @max_price = @max_price.to_f > 10000 ? @max_price : 10000
    @gatherings = @gatherings.paginate(:page => params[:page], :per_page => 6 )
    respond_to do |format| 
      format.html
      format.js do
        foo = render_to_string(:partial => 'gatherings', :locals => { :offers => @gatherings,:params => params }).to_json
        render :js => "update_gathering_values('#{params.to_json}');$('#searched-gatherings').html(#{foo});$.setAjaxPagination();"
      end
    end
  end

  def members
    @users_with_uniq_cities = Item.select("distinct(city)").where("city is not NULL and city != ''")
    @users_with_uniq_activites = User.select("distinct(activity)").where("activity is not NULL and activity != ''")
    @members = User.find(:all)
    @members = @members.paginate(:page => params[:page], :per_page => 6 )
  end
  
  def spaces    
    @users_with_uniq_cities = Item.select("distinct(city)").where("city is not NULL and city != ''")
    @types = ListingType.select("distinct(name), id").where("name is not NULL")
    @types << {"Other"=>"Other"}
    
    session[:start_date] = nil
    session[:end_date] = nil
    
    @sizes = Item.select("distinct(size)").where("size is not NULL").order("size ASC")
    @types = ListingType.select("distinct(name), id").where("name is not NULL")
    @shareable = Item.select("distinct(is_shareable)")    
    
    @start_size = @sizes.first.size
    @last_size = @sizes.last.size
    @start_size = @start_size.blank? ? 1 : @start_size.size
    
    @start_price = @items.blank? ? 1 : @items.first.price
    @last_price = @items.blank? ? 1 : @items.last.price
    
    unless @last_size.blank?
      @last_size = @last_size.size.to_f > 10000 ? @last_size.size : 10000
    else
      @last_size = 10000
    end

    @last_price = @last_price.to_f > 10000 ? @last_price : 10000
    #    Conditions on Items search
    item_conds = "1=1 "
    
    unless params[:search_from].blank?
      start_time =  DateTime.strptime(params[:search_from], "%m/%d/%Y").to_date
      item_conds += " AND ( ('#{start_time.to_s}' >= availability_from OR '#{start_time.to_s}' <= availability_to) OR (available_forever = true))"
    end
    
    unless params[:search_to].blank?
      end_time =  DateTime.strptime(params[:search_to], "%m/%d/%Y").to_date
      item_conds += " AND ( ('#{end_time.to_s}' >= availability_from  OR '#{end_time.to_s}' <= availability_to ) OR (available_forever = true))"
    end
    
    if !params[:search_from].blank? and !params[:search_to].blank?
      item_conds += " AND ( ( ( availability_from between '#{start_time.to_s}' and '#{end_time.to_s}') or ( availability_to between '#{start_time.to_s}' and '#{end_time.to_s}')  ) OR (available_forever = true))"
    end
       
    if params[:search_from].blank? and params[:search_to].blank?
      item_conds += " AND (('#{Date.today.to_s}' between availability_from and availability_to) OR (available_forever = true))"
    end
    
    if !params[:min_price].blank? and !params[:max_price].blank?
      item_conds += "AND price >= '#{params[:min_price].to_f}' AND price <= '#{params[:max_price].to_f}'"
    end    
    
    unless params[:location].blank?
      item_conds += " AND (city LIKE " + "'%%" + "#{params[:location]}" + "%%'" +")"
    end
        
    unless params[:min_size].blank?
      item_conds += " AND (size >= '#{params[:min_size].to_i}')"
    end
    
    unless params[:max_size].blank?
      item_conds += " AND (size <= '#{params[:max_size].to_i}')"
    end
        
    unless params["types"].blank?
      count = 0
      type_arr = ""
      params["types"].each do|type|        
        if count == 0
          type_arr += " listing_type_id = '#{type}'"
        else
          type_arr += " OR listing_type_id = '#{type}'"
        end
        count += 1
      end
      item_conds += " AND (#{type_arr})"
    end
    
    if params[:shareable] == "true"
      item_conds += " AND (is_shareable = true)"
    elsif params[:shareable] == "false"
      item_conds += " AND (is_shareable = false)"
    end
    
    case params[:sort_option]
    when "1"
      order_by = "created_at DESC"
    when "2"
      order_by = "price DESC"
    when "3"
      order_by = "price ASC"
    when "4"
      order_by = "created_at DESC"
    else
      order_by = "price ASC"
    end
    
    items = Item.find(:all,:conditions => [ item_conds ], :order => order_by)    

    #    @items = items - booked_items    
    @items = items
    # Items whose owners are active users
    active_items = []  
    @items.each do|item|
      if item.user.is_active == true && item.is_active == true
        active_items << item
      end
    end
    @items = active_items
    
    if params[:sort_option].blank?
      @items = @items.sort_by{|e| e[:price]}
    end
    
    if params[:sort_option].blank?
      @items = @items.sort_by{|e| e[:size]}
    end
    session[:start_date] = params[:search_from]
    session[:end_date] = params[:search_to]
    @vals = params
    @items = @items.paginate(:page => params[:page], :per_page => 6, :order => "created_at DESC" )
    respond_to do |format|
      format.html
      format.js do
        foo = render_to_string(:partial => 'items', :locals => { :items => @items, :params => params }).to_json
        render :js => "$('#searched-items').html(#{foo});$.setAjaxPagination();"
      end
    end
  end
  
  def search_spaces
    session[:start_date] = nil
    session[:end_date] = nil
      
    @sizes = Item.select("distinct(size)").where("size is not NULL").order("size ASC")
    @types = ListingType.select("distinct(name), id").where("name is not NULL")
    @shareable = Item.select("distinct(is_shareable)")    
    
    @start_size = @sizes.first.size
    @last_size = @sizes.last.size
    @start_size = @start_size.blank? ? 1 : @start_size.size
    
    @start_price = @items.blank? ? 1 : @items.first.price
    @last_price = @items.blank? ? 1 : @items.last.price
    
    unless @last_size.blank?
      @last_size = @last_size.size.to_f > 10000 ? @last_size.size : 10000
    else

app/helpers/search_helper.rb
module SearchHelper
end

app/views/searches/_favorite.html.erb
<%if !current_user%>
  <%= link_to image_tag("/assets/star_empty.png", :width => "18", :height => "18", :alt => "Add to Favorites"), "#", :onclick=> "return no_login()" %>
<%elsif current_user.favorites.include?(item)%>
  <%= link_to image_tag("/assets/blue-star.png", :width => "18", :height => "18", :alt => "Add to Favorites"), remove_from_favorite_item_path(item), :class => "linkAddRmFavorite", :style => "padding-top:0px !important", :remote => true %>
<%else%>
  <%= link_to image_tag("/assets/star_empty.png", :width => "18", :height => "18", :alt => "Add to Favorites"), add_to_favorite_item_path(item), :class => "linkAddRmFavorite", :style => "padding-top:0px !important", :remote => true %>
<%end%>
<script>
  function no_login()
  {
    alert("You should login to use this feature");
    return false;
  }
</script>

app/views/searches/_member_rating.html.erb
<% asset = member %>
<ul class='star-rating'>
  <% if !(user_signed_in?)%>
    <li class="current-rating" style="width:<%= ( member.accuracy_rating * 20).to_i -%>px;" />
  <%else%>
    <%if member == current_user %>
      <li class='current-rating' style='width:<%= (member.accuracy_rating * 20).to_i -%>px;' />
    <% else %>
      <li class='current-rating' style='width:<%= (member.accuracy_rating * 20).to_i -%>px;' />
      <li>
        <%= link_to_function "#", only_view == false ? "send_rating('/searches/user_rating?id=#{asset.id}&accuracy_rating=1&class_name=#{asset.class}', 'accuracy_rating','#{asset.id}');" : "javascript:void(0);" ,
          :class => 'one-star', :name => '1 star out of 5' %>
      </li>
      <li>
        <%= link_to_function "#", only_view == false ? "send_rating('/searches/user_rating?id=#{asset.id}&accuracy_rating=2&class_name=#{asset.class}', 'accuracy_rating','#{asset.id}');" : "javascript:void(0);" ,
          :class => 'two-stars', :name => '2 stars out of 5' %>
      </li>
      <li>
        <%= link_to_function "#", only_view == false ? "send_rating('/searches/user_rating?id=#{asset.id}&accuracy_rating=3&class_name=#{asset.class}', 'accuracy_rating','#{asset.id}');" : "javascript:void(0);" ,
          :class => 'three-stars', :name => '3 stars out of 5' %>
      </li>
      <li>
        <%= link_to_function "#", only_view == false ? "send_rating('/searches/user_rating?id=#{asset.id}&accuracy_rating=4&class_name=#{asset.class}', 'accuracy_rating','#{asset.id}');" : "javascript:void(0);" ,
          :class => 'four-stars', :name => '4 stars out of 5' %>
      </li>
      <li>
        <%= link_to_function "#", only_view == false ? "send_rating('/searches/user_rating?id=#{asset.id}&accuracy_rating=5&class_name=#{asset.class}', 'accuracy_rating','#{asset.id}');" : "javascript:void(0);" ,
          :class => 'five-stars', :name => '5 stars out of 5' %>
      </li>
    <%end%>
  <%end%>
</ul>

app/views/searches/_members.html.erb
<div class="listx-bg">
  <div class="sortby">    
    <span style="float:right;">
      <%= will_paginate(@members, :params => params, :renderer => PaginationListLinkRenderer) %>
    </span>
  </div>
</div>
<div class="resultsholderlist shadowCont">
  <% members.each do | member | %>    
    <div class="listx" style="border-bottom: 1px solid gray;padding: 5px;float: left;">

      <div class="row" style="float:left; width: 732px;">
        <div class="imgx" onclick="window.location='<%= profile_path(member.id) %>'">
          <% if member.avatars.size > 0 %>
            <%= image_tag(member.avatars.first.photo.url(:thumb), :width => "113", :height => "149", :alt => "Member-Photo")  %>
          <% else %>
            <%= image_tag("empty.png", :width => "113", :height => "147", :alt => "Member-Photo")  %>
          <% end %>
        </div>

        <div class="name-list" style="margin-bottom: 5px;">
          <h4 style="font-family:proxima-bold; color: #333333;">
            <%= member.first_name + " " + member.last_name %>
            <div id="rating_of_user_<%= member.id %>" >
              <%= render :partial => "member_rating", :locals => {:member => member, :only_view => false} %>
            </div>
          </h4>
        </div>

        <div class="name-list" style="margin-bottom: 5px; color: #666666; font-family: proxima-semibold; font-size: 1.2em;" onclick="window.location='<%= profile_path(member.id) %>'">
          <%= member.activity %>
        </div>

        <div onclick="window.location='<%= profile_path(member.id) %>'" class="name-list XXII" style="margin-bottom: 5px;">
          <% unless member.city.blank? %>
            <%= member.city %>
          <% end %>
          <% unless member.country.blank? %>
            <%= member.country %>
          <% end %>
        </div>
      </div>

      <div style="margin-top: -30px; color: grey;float: right;">
        <% if (current_user != member) %>
          <%= link_to_function "Send Message", "$('#contact_me_div_#{member.id}').toggle('slow');", :class => "send", :style => "margin-top: 35px;" %>
        <% end %>

        <div style="float: left;width: 100%;margin-top: 10px;display: none;" id="contact_me_div_<%= member.id %>">
          <%= form_tag contact_me_messages_path , :html => {:id => "contact_me_form"}, :remote  => true do %>
            <%= hidden_field_tag :topic, "Inquiry" %>
            <%= hidden_field_tag :user_id, member.id %>

            <span style="width: auto;float: left;">
              <%= text_area_tag  :body, "", :style => "width:135px; height:100px;" %>
            </span>

            <div style="margin-right: 10px; text-align: right;">
              <%= submit_tag "Send", :onclick => "$('#contact_me_div_#{member.id}').hide();" %>&nbsp;&nbsp;&nbsp;
              <%= link_to_function "Cancel", "$('#contact_me_div_#{member.id}').toggle('slow');"  %>
            </div>
          <% end %>
        </div>
        <div class="clear"></div>
      </div>
    </div>
  <%end%>
</div>

app/views/searches/_search_header.html.erb
<div id="bar-searchaction" class="menu-sub-layout" >
  <div class="menu-sub" style="background-color: <%= ((params[:action] == "search_keyword") or (params[:action] == "spaces") or (params[:action] == "search_spaces") or (params[:controller] == "items" and params[:action] == "show")) ? "cyan" : '' %>">
    <%= link_to t(:spaces3), spaces_searches_path %>
  </div>

  <div class="menu-sub" style="background-color: <%= (params[:action] == 'gatherings' || params[:action] == 'search_gatherings') ? "cyan" : '' %>">
    <%= link_to t(:pop_unions), gatherings_searches_path %>
  </div>    

  <div class="menu-sub" style="background-color: <%= (params[:action] == 'members' or params[:action] == 'search_members') ? "cyan" : '' %>">
    <%= link_to t(:mem), members_searches_path %>
  </div>
</div>

app/views/searches/members.html.erb
<%= render :partial => "search_header" %>
<div class="clear"></div>

<div class="rightcontent shadowCont" style="padding: 5px 20px 20px;">
  <h2 style="font-size: 1.4em; font-weight: normal; font-family:proxima-semibold;"><%= t(:refine_search) %></h2>
  <%= form_tag "/searches/search_members", {:remote => true, :id => "price_range_form", :pars => params } do %>
    <%= hidden_field_tag "location",  '', :id => "searched_member_location" %>
    <%= hidden_field_tag "user", '', :id => "searched_member_name" %>

    <div class="pannelright">
      <div class="heading_right"><%= t(:active3)%></div>
      <div class="twocol">
        <% @users_with_uniq_activites.each do |type| %>
          <%= check_box_tag 'types[]', type.activity, params["types"].blank? ? false : params["types"].include?(type.activity.to_s), :onclick => "$('#search_submit').trigger('click')" %>
          <%= type.activity.capitalize %><br />
        <% end %>
      </div>
      <%= submit_tag "Submit", :hidden => true, :id => "search_submit" %>
    </div>

  <% end %>
</div>

<div class="leftcontent">
  <%= form_for :search, :url => search_members_searches_path, :remote => true do|f|%>
    <div class="refinesearchresults shadowCont">
      <h2 style="font-size: 21px;margin-bottom: 10px; font-weight: normal; font-family:proxima-semibold;"><%= t(:mem_search)%></h2>
      <div>
        <div style="width:92%;float:left;">
          <div style="float: left;width: 70%;">
            <%= text_field_tag "user", "",:style=>["width:320px"], :hint => "Enter member name or email" %>
          </div>
          <div class="refinesearchresults1" style="float: left;width: 30%;height: 0px;margin-top: 0px !important;">
            <span>Change City</span>
            <div style="float:right;position: absolute;text-align: center;">
              <%= select_tag( "location", options_from_collection_for_select( @users_with_uniq_cities, :city, :city), :prompt => "World Wide", :class => "paris") %>
            </div>
          </div>
        </div>

        <%= image_submit_tag("Objet-dynamique-vectoriel1-.png") %>
      </div>
    </div>    
  <% end %>

  <div id="searched-members" class="listx-bg">
    <% unless @members.blank? %>
      <%= render :partial => "members", :locals => {:members => @members, :only_view => false} %>
    <% else %>
      <%= t(:no_member_given) %>
    <% end %>
  </div>
</div>

<script type="text/javascript">
  $(function() {
    $('#search_from').datepicker(
    {
      onSelect: function() {
        $('#search_to').datepicker('option', {minDate: $(this).datepicker('getDate')});
      }});
    $('#search_to').datepicker({
      onSelect: function() {
        $('#search_from').datepicker('option', {maxDate: $(this).datepicker('getDate')});
      }});
  
  });
  function update_member_values(params){
    var str = $.parseJSON(params);
    $("#searched_member_location").attr("value",str.location.toString());
    $("#searched_member_user").attr("value",str.user.toString());
  }
  $(document).ready(function() {
    <%#*$('.pagination a').attr('data-remote', 'true');%>
    $('#location').chosen();
  });
</script>
<script type="text/javascript">
  function send_rating(rating_url, mode,asset){
    jQuery.ajax({
      type:"GET",
      url: rating_url,
      data: ({'rate': true })
      
    });
  }
</script>

app/views/searches/search_members.html.erb
<div id="get-list-header">
  <h2>Members</h2>
</div>
<div class="listx-bg">
  <% unless @members.blank? %>
    <% @members.each do | member | %>
      <div class="listx" style="margin-bottom: 10px;border-bottom: 1px solid gray;padding: 10px;">
        <div class="imgx">
          <% if member.avatars.size > 0 %>
            <%= link_to image_tag(member.avatars.first.photo.url(:thumb), :width => "105", :height => "105", :alt => "Space-Photo"), profile_path(member.id) %>
          <% else %>
            NO IMAGE PROVIDED YET.
          <% end %>
        </div>

        <div class="name-list">
          <b>Name:</b>
          <%=link_to "#{member.first_name + " " + member.last_name}", profile_path(member.id) %>
        </div>

        <div class="name-list">
          <b>Activity:</b>
          <%= member.activity %>
        </div>

        <div class="name-list">
          <b>City:</b>
          <%= member.city %>
        </div>

        <div class="name-list">
          <b>Country:</b>
          <%= member.country %>
        </div>
        <div class="manage-bg">
        </div>
      </div>
    <%end%>
  <%else%>
    No Member with given criteria found!
  <%end%>
</div>

<div class="btn-bar">

</div>