config/routes.rb
# -*- encoding : utf-8 -*-
PopupStorz::Application.routes.draw do
  get "users/show"

  match "/users/update" => "users#update"
  match '/auth/:provider/callback' => 'services#create'
  match '/auth/facebook/callback' => 'services#create'
  match '/auth/twitter/callback' => 'services#create'
  match '/items/search_keyword' => 'items#search_keyword'
  match '/items/search_category/:id' => 'items#search_category'
  match '/notifications/destroy/:id' => 'notifications#destroy'
  match '/members' => 'users#members'
  match '/admin_items' => "admin/items#index"
  match '/admin_gatherings' => "admin/offers#gatherings"
  match '/admin/users/create' => "admin/users#create"
  match '/admin_send_invitations' => "admin/users#send_invitations"
  #  match '/search_members' => 'users#search_members'
  match '/search_gatherings' => 'searches#search_gatherings'
  match '/search_spaces' => 'searches#search_spaces'
  match '/admin_destroy_user/:id' => "admin/users#destroy_user"
  match '/admin_edit_user/:id' => "admin/users#edit"
  match '/admin_users' => "admin/users#index"
  match '/delete_listings' => "admin/items#delete_listings"
  match "/search_via_price_range" => "items#search_via_price_range"
  match "/items/new/:id" => "items#new_comment"
  match "/items/add_comment" => "items#add_comment"
  match "/items/show/:id" => "items#show"
  match "/users/add_comment" => "users#add_comment"
  match "/items/pop_ups" => "items#my_pop_ups"
  match "/home/terms" => "home#terms"
  match "/home/contact" => "home#contact"
  match "/home/feedback" => "home#feedback"
  match "/home/send_feedback" => "home#send_feedback"
  match "/email_settings" => "email_settings#index"
  
  match "/items/payment_charge/:id" => "items#payment_charge"
  match "/home/pay" => "home#pay"
  match "/join_gathering/:id" => "offers#join_gathering"
  match "/join/:id" => "offers#join"
  match "/approve_gathering_request/:id" => "offers#approve_gathering_request"
  match "/decline_gathering_request/:id" => "offers#decline_gathering_request"
  match "/accept_gathering/:id" => "offers#accept"
  match "/reject_gathering/:id" => "offers#decline"
  match "/products/cancelled_payment_request" => "products#cancelled_payment_request", :as  => :cancel_request
  match "products/completed_payment_request" => "products#completed_payment_request", :as => :complete_request
  match "/send_invitation" => "users#send_invitation"
  match "/invitation" => "users#invitations"
  match "/users/callback" => "users#callback"
  match "/users/send_invitation_to_contacts" => "users#send_invitation_to_contacts"
  match "/contacts/failure" => "users#send_invitation_to_contacts"
  
  match "/email_settings/index" => "email_settings#index"
  match "/email_settings/show" => "email_settings#show"
  match "/email_settings/create" => "email_settings#create"
  match "/email_settings/edit" => "email_settings#edit"
  match "/email_settings/update/:id" => "email_settings#update"
  match "/users/deactivate_account" => "users#deactivate_account"
  match "/send_resposne_request" => "offers#send_resposne_request"
  match "/send_gathering_deadline/:id" => "offers#send_gathering_deadline"
  match "/update_gathering_deadline" => "offers#update_gathering_deadline"
  match "/pending_gathering_acceptance" => "offers#pending_gathering_acceptance"
  match "/offers/add_comment" => "offers#add_comment"
  match "/cancel_booking/:id" => "offers#cancel_booking"
  match "/searches/user_rating" => "searches#user_rating"
  
  devise_for :users, :controllers => {:registrations => "registrations"}

  resources :accounts do
    collection do
      get 'verification_selection'
    end
  end

  resources :searches do
    collection do
      get "search_home"
      get "gatherings"
      get "members"
      get "spaces"
      post "search_gatherings"
      post "search_members"
      post "search_spaces"
    end
  end
  
  resources :email_settings do    
  end

  match '/items/set_dates' => "items#set_dates", :as => :set_dates
  match '/items/exchange_price' => "items#exchange_price", :as => :exchange_price

  resources :ratings do
    collection do
      get "rate"
      post "rate"
    end
  end
  
  resources :messages do
    collection do
      get 'inbox'
      get 'compose'
      get 'sent_items'
      get 'trash'      
      get 'delete'
      get 'empty_trash'
      get 'reply'

      post 'do_reply'
      post 'manage'
      post 'send_message'
      post 'contact_me'
      post 'gathering_message'
    end
  end

  match "account/:id/dashboard" => "accounts#dashboard",  :as  => :dashboard
  match "accept_invitation/:id" => "invitations#accept_invitation",  :as  => :accept_invitation
  match '/sign_out' => 'devise/sessions#destroy'

  devise_for :users do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  get "home/index"
  get "home/about"
  get "items/new"
  
  namespace :admin do
    resources :items do
      collection do
        get :change_recommendation
        post :transfer_ownership
        post :change_commission_rate
        get :change_rate
        post :change_all
        post :display_on_home
        get :active_inactive
        get :offer_activation
      end      
    end
    resources :users do
      collection do
        get :delete_message
        get :all_messages
        post :all_messages
        get :all_feedbacks
        post :all_feedbacks
        get :all_ratings
        get :delete_rating
        get :delete_comment
        #        get :send_invitation
        get :invitations
        post :send_invitation_to_users
        post :send_invitations
        post :send_invitation
        get :all_payments
        get :cancel_payment
#        get :all_feedbacks        
      end
    end
    resources :offers do
      collection do
        post :change_commission_rate
        post :add_comment
      end
    end
    resources :messages do
      collection do
        get :send_to_all
        post :send_message_to_all
        post :send_message_to_user
        get :send_message
      end
    end
  end
  resources :services do
    get "/services/create/:id" => "services#create"
  end
  resources :invitations do
    collection do
      get :fetch
      post :fetch
      post :send_emails
    end
  end

  namespace :xml do
    match 'location_search.xml' => 'LocationSearch#index', :format => :xml
    match 'address_search.xml'  => 'AddressSearch#index' , :format => :xml
  end

  resources :ratings do
    collection do
      get "rate"
      post "rate"
    end
  end
  resources :offers
  resources :avatars
  resources :items do
    collection do
      get "overview"
      get "created_prev_gatherings"
      get "created_coming_gatherings"
      get "pending_gathering_acceptance"
      get "gatherings_at_my_place"
      get "listings_home"
      get "past_transactions"
      get "search_item_spaces"
    end
    resources :avatars
    collection do
      get "sent_requests"      
    end
    get :autocomplete_item_title, :on => :collection
    get :autocomplete_item_city, :on => :collection
    get :add_to_favorite, :on => :member
    get :remove_from_favorite, :on => :member
    get :remove_from_favorite_on, :on => :member
    get :favorites, :on => :collection
    resources :offers do
      resources :payments
      member do
        get 'decline'
        get 'accept'
      end
    end
  end
  
  match '/users/:id/profile' => 'users#show', :as => :profile
  match '/users/:id/profile/edit' => 'users#edit', :as => :edit_profile
  match 'admin/users/:id/profile' => 'admin/users#show', :as => :admin_profile
  root :to => "home#index"
end

app/controllers/admin/users_controller.rb
# -*- encoding : utf-8 -*-
class Admin::UsersController < ApplicationController
  before_filter :authenticate_admin
  layout "admin"

  def index
    case params[:sort_option]
    when "1"
      order_by = "created_at DESC"
    when "2"
      order_by = "created_at ASC"
    when "3"
      order_by = "activity ASC"
    when "4"
      order_by = "gender DESC"
    when "5"
      order_by = "city ASC"
    when "6"
      order_by = "country ASC"
    when "7"
      order_by = "show_fb_info"
    when "8"
      order_by = "last_name ASC"
    else
      order_by = "created_at DESC"
    end
    @users = User.all(:order => order_by)
    respond_to do |format|
      format.js do
        foo = render_to_string(:partial => 'users', :locals => { :users => @users }).to_json
        render :js => "$('#users_list').html(#{foo});"
      end
      format.html
    end
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    @user.skip_confirmation!
    if @user.save
      UserMailer.send_user_information(@user).deliver
      redirect_to admin_users_path
    else
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
  end
  
  def edit
    @user = User.find(params[:id])
  end
  
  def update
    @user = User.find(params[:id])
    params[:user][:verify_email] = params[:user][:email]
    if params[:user][:password].blank? && params[:user][:password_confirmation].blank?
      params[:user].delete(:password)
      params[:user].delete(:password_confirmation)
    end
    if @user.update_attributes(params[:user])
      flash[:notice] = "User updated successfully!"
      redirect_to admin_users_path
    else
      flash[:error] = "User can't be updated. Please try again or later!"
      render :edit
    end    
  end

  def destroy_user
    user = User.find(params[:id])
    user.update_attribute(:is_active, !user.is_active)
    redirect_to admin_users_path
  end

  def all_messages
    searched_users = []
    users_arr = []
    @messages = []
    case params[:sort_option]
    when "1"      
      order_by = "created_at DESC"
      @messages = ActsAsMessageable::Message.all(:order => order_by)
    when "2"
      searched_users = ActsAsMessageable::Message.select("received_messageable_id")
      unless searched_users.blank?        
        searched_users.each do|r|
          users_arr << r.received_messageable_id
        end
        users_arr = users_arr.uniq
      end
      users = User.find(:all, :conditions => ["users.id IN (?)",users_arr], :order => "first_name ASC")      
      users.each do|u|
        msgs = ActsAsMessageable::Message.all(:conditions => ["received_messageable_id = ?",u.id])
        msgs.each do|m|
          @messages << m
        end
      end
    when "3"
      searched_users = ActsAsMessageable::Message.select("sent_messageable_id")
      unless searched_users.blank?
        searched_users.each do|r|
          users_arr << r.sent_messageable_id
        end
        users_arr = users_arr.uniq
      end
      users = User.find(:all, :conditions => ["users.id IN (?)",users_arr], :order => "first_name ASC")      
      users.each do|u|
        @messages << ActsAsMessageable::Message.all(:conditions => ["sent_messageable_id = ?",u.id])
      end
      @messages = @messages.first
    else
      order_by = "created_at ASC"
      @messages = ActsAsMessageable::Message.all(:order => order_by)
    end
    
    respond_to do |format|
      format.js do
        foo = render_to_string(:partial => 'messages', :locals => {:messages => @messages }).to_json
        render :js => "$('#admin_messages_list').html(#{foo});"
      end
      format.html
    end    
  end

  def delete_message
    #    @messages = ActsAsMessageable::Message.all
    @msg= ActsAsMessageable::Message.find_by_id(params[:id])
    @msg.destroy
    redirect_to all_messages_admin_users_path
  end

  def all_feedbacks
    users_arr = []
    @comments = []
    case params[:sort_option]
    when "1"      
      order_by = "created_at DESC"
      @comments = Comment.all(:order => order_by)
    when "2"
      users = Comment.select("user_id")
      unless users.blank?        
        users.each do|u|
          users_arr << u.user_id
        end
        users_arr = users_arr.uniq
      end
      users = User.find(:all, :conditions => ["users.id IN (?)",users_arr], :order => "first_name ASC")      
      users.each do|u|
        cmnts = Comment.all(:conditions => ["user_id = ?",u.id])
        unless cmnts.blank?
          cmnts.each do|c|
            @comments << c
          end
        end
      end
    else
      order_by = "created_at ASC"
      @comments = Comment.all(:order => order_by)
    end
    
    respond_to do |format|
      format.js do
        foo = render_to_string(:partial => 'feedbacks', :locals => { :comments => @comments }).to_json
        render :js => "$('#admin_feedbacks_list').html(#{foo});"
      end
      format.html
    end
  end
  
  def all_ratings
    @ratings = Rating.all
  end

  def delete_rating
    @rating = Rating.find_by_id(params[:id])
    @rating.destroy
    redirect_to all_ratings_admin_users_path
  end
  
  def delete_rating
    @comment = Comment.find_by_id(params[:id])
    @comment.destroy
    redirect_to all_comments_admin_users_path
  end

  def send_invitation
    (1..10).each do |i|
      unless params["email"+"#{i}"].blank?
        @invitation = Invitation.new
        @invitation.user = current_user
        @invitation.email = params["email"+"#{i}"]
        @invitation.token = (Digest::MD5.hexdigest "#{ActiveSupport::SecureRandom.hex(10)}-#{DateTime.now.to_s}")
        @invitation.save
        UserMailer.send_admin_invitation_email(@invitation,params["fname"+"#{i}"],params["lname"+"#{i}"],params[:message]).deliver
      end
    end
    flash[:notice] = t(:invitation_sent)
    redirect_to admin_users_path
  end

  #  def send_invitation_to_users
  #    unless params[:user].blank?
  #      params[:user][0].split(',').each do |val|
  #        unless val.blank?
  #          @invitation = Invitation.new
  #          @invitation.user = current_user
  #          @invitation.email = val
  #          @invitation.token = (Digest::MD5.hexdigest "#{ActiveSupport::SecureRandom.hex(10)}-#{DateTime.now.to_s}")
  #          @invitation.save
  #          UserMailer.send_invitation_email(@invitation).deliver
  #        end
  #      end
  #    end    
  #    redirect_to admin_items_path
  #  end

  def all_payments
    @payments = Payment.all
  end

  def cancel_payment
    @payment = Payment.find_by_id(params[:id])
    @payment.update_attribute(:cancelled_at, date.today)
    @payment.update_attribute(:is_active, !user.is_active)
    redirect_to all_payments_admin_users_path
  end
  
  #  def send_invitations
  #    (1..10).each do |i|
  #      unless params["email"+"#{i}"].blank?
  #        @invitation = Invitation.new
  #        @invitation.user = current_user      
  #        @invitation.email = params["email"+"#{i}"]
  #        @invitation.token = (Digest::MD5.hexdigest "#{ActiveSupport::SecureRandom.hex(10)}-#{DateTime.now.to_s}")
  #        @invitation.save
  #        UserMailer.send_admin_invitation_email(@invitation,params[:additional_message]).deliver
  #      end
  #    end
  #    flash[:notice] = t(:invitation_sent)
  #    redirect_to admin_users_path
  #  end
  
end

app/helpers/users_helper.rb
# -*- encoding : utf-8 -*-
module UsersHelper
end

app/views/admin/users/_feedbacks.html.erb
<div class="listx-bg">
  <% unless comments.blank? %>
    <% comments.each do |comment| %>
      <% if comment.commentable_type == "Offer" %>
        <% @offer = Offer.find_by_id(comment.commentable_type) %>
        <%= t(:title) %>: <%= comment.title %><br />
        <%= t(:comment) %>: <%= raw comment.comment %><br />
        <%= t(:commented_by) %>: <%= comment.user.first_name %> <%= comment.user.last_name %><br/>
        
        <%=link_to t(:delete_comment), delete_comment_admin_users_path(:id => comment.id), :confirm => "Are you sure!" %><br/>

      <% end %>
      <br/><br/><br/>
    <%end%>
  <%else%>
    <%= t(:no_comments) %>
  <%end%>
</div>

app/views/admin/users/_messages.html.erb
<div class="listx-bg">
  <%unless messages.blank? %>  
    <% messages.each do |msg|%>
      <% @sender = User.find_by_id(msg.sent_messageable_id) %>
      <% @receiver = User.find_by_id(msg.received_messageable_id) %>
      <%= t(:message_body) %> :<%= raw(msg.body) %><br/>
      <%= t(:sender) %> : <%= @sender.first_name %> <%= @sender.last_name %><br/>
      <%= t(:receiver) %> : <%= @receiver.first_name %> <%= @receiver.last_name %><br/>
      <%= link_to t(:delete_message), delete_message_admin_users_path(:id => msg.id), :confirm => "Are you sure!"%>
      <br/><br/><br/>
    <%end%>
  <%else%>
    There are no messages to show!
  <%end%>
</div>

app/views/admin/users/_users.html.erb
<% unless users.blank? %>
  <% users.each do | user | %>
    <div class="listx" style="margin-bottom: 10px;border-bottom: 1px solid gray;padding: 10px;">
      <div class="name-list"><%= user.email %> - <%= user.first_name %> <%= user.last_name %></div>
      <div class="manage-bg">
        <div class="btns">
          <%= link_to t(:details) , admin_profile_path(user)%>
        </div>
        <div class="btns">
          <% if user.is_active %>
            <%= link_to t(:deactivate) , "/admin_destroy_user/#{user.id}", :confirm => "Are you sure"%>|
          <% else %>
            <%= link_to t(:activate) , "/admin_destroy_user/#{user.id}", :confirm => "Are you sure"%>|
          <% end %>
          <%= link_to t(:edit), "/admin_edit_user/#{user.id}" %>|
          <%= link_to t(:send_message), send_message_admin_messages_path(:user_id => user.id) %>
        </div>
      </div>
    </div>
  <% end %>
<% else %>
  <%= t(:no_user_registered) %>
<% end %>

app/views/admin/users/all_feedbacks.html.erb
<div id="get-list-header">
  <h2><%= t(:all_feedbacks)%></h2>
</div>
<div style="float:left;width: 100%;margin-bottom: 20px;margin-top: 20px;margin-left: 10px;">
  <%= form_for :search, :url => all_feedbacks_admin_users_path, :remote => true do |f| %>
    <span><%= t(:sort_by) %></span>  
    <%= select_tag "sort_option", options_for_select([[t(:by_date) ,"1"],[t(:by_name) ,"2"]], params[:sort_option]), :prompt => "Sort By",:onchange => "$(this.form).submit()" %>
  <% end %>
</div>
<div class="listx-bg" id="admin_feedbacks_list">
  <%= render :partial => "feedbacks", :locals => {:comments => @comments} %>
</div>

app/views/admin/users/all_payments.html.erb
<div id="get-list-header">
  <h2><%= t(:all_payments) %></h2>
</div>

<br/>
<div>
  <%unless @payments.blank?%>
    <%@payments.each do |payment|%>
      <%@seller = User.find_by_id(payment.seller_id)%>
      <%@renter = User.find_by_id(payment.renter_id)%>
      <%= t(:seller) %>: <%= @seller.first_name %> <%= @seller.last_name %><br/>
      <%= t(:renter) %>: <%= @renter.first_name %> <%= @renter.last_name %><br/>
      <%if payment.is_active %>
        <%if payment.is_active%>
          <%= link_to t(:deactivate), cancel_payment_admin_users_path(:id => payment.id), :confirm => "Are you sure" %>
        <%else%>
          <%= link_to t(:activate), cancel_payment_admin_users_path(:id => payment.id), :confirm => "Are you sure" %>
        <%end%>
      <%end%>
    <%end%>
  <%else%>
    <%= t(:no_payments) %>
  <%end%>
</div>

app/views/admin/users/invitations.html.erb
<script type="text/javascript">
  function check_email() {
    
    email1 = $("#email1").val();
    email2 = $("#email2").val();
    email3 = $("#email3").val();
    email4 = $("#email4").val();
    email5 = $("#email5").val();
    email6 = $("#email6").val();
    email7 = $("#email7").val();
    email8 = $("#email8").val();
    email9 = $("#email9").val();
    email10 = $("#email10").val();
    
    if(email1 == "" && email2 == "" && email3 == "" && email4 == "" && email5 == "" && email6 == "" && email7 == "" && email8 == ""&& email9 == "" && email10 == ""){
      alert("Please insert some email addresses first");
      return false;
    }
    var regex = /^([a-zA-Z0-9_\.\-\+])+\@(([a-zA-Z0-9\-])+\.)+([a-zA-Z0-9]{2,4})+$/;
    
    
    for(var i=1;i<=10;i++){
      if($("#email"+i).val() != ""){
        if(regex.test($("#email"+i).val()) ==  false){
          alert("Invalid Email Address");
          $("#email"+i).css("border-color", "red");
          return false;
        }
      }
    }
    return true;
  }
</script>
<br/>

<%#*<div style="float: left;width: 100%;border: 1px solid black;padding: 5px;">%>
  <%#*<h2>%>
    <%#*<span style="float: left;padding: 5px;background-color: <%= (params[:action] == 'send_invitation' or params[:action] == 'invitations') ? 'silver' : '' %>
      <%#= link_to 'Send Inivtations', invitation_path, :class => ((params[:controller] == "users" and ( params[:action] == "send_invitations" or params[:action] == "invitations" )) ? "m_act" : "") %>
    <%#*</span>%>
    <%#*<span style="float: left;padding: 5px">%>
      <%#*&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;%>
    <%#*</span>%>
    <%#*<span style="float: left;padding: 5px;background-color: <%= (params[:action] == 'index' or params[:action] == 'new') ? 'silver' : '' %>
      <%#= link_to 'Email Settings', email_settings_path, :class => ((params[:controller] == "email_settings" and ( params[:action] == "index" or params[:action] == "new" )) ? "m_act" : "") %>
    <%#*</span>%>
    <%#*<span style="float: left;padding: 5px">%>
      <%#*&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;%>
    <%#*</span>%>
    <%#*<span style="float: left;padding: 5px">%>
      <%#= link_to t(:delete_my_account),"/users/delete_account", :confirm => t(:delete_permanently) %>
    <%#*</span>%>
    <%#*<span style="float: left;padding: 5px">%>
      <%#*&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;%>
    <%#*</span>%>
    <%#*<span style="float: left;padding: 5px">%>
      <%#= link_to "send invitation to contacts in your email account","/users/send_invitation_to_contacts", :class => (params[:controller] == "users" and params[:action] == "send_invitation_to_contacts"  ? "m_act" : "") %>
    <%#*</span>%>
  <%#*</h2>%>
<%#*</div>%>

<div style="float: left;width: 100%;margin-top: 10px;" id="invitation_div">
  <%= form_tag "send_invitation", :url => "/admin_send_invitations" , :onsubmit => "return check_email();" do %>
    <%= hidden_field_tag :user_id, current_user.id %>
    <span style="width: auto;float: left;">

      <div class="xfields"><%= t(:send_invite) %></div>
      <div class="xfields">
        <%= text_field_tag "fname1", nil, "hint" => "First name", :class => "input", :style => "width: 175px;" %>
        <%= text_field_tag "lname1", nil, "hint" => "Last name", :class => "input", :style => "width: 175px;" %>
        <%= text_field_tag "email1", nil, "hint" => "E-mail address", :class => "input", :style => "width: 175px;" %>
      </div>
      <div class="xfields">
        <%= text_field_tag "fname2", nil, "hint" => "First name", :class => "input", :style => "width: 175px;" %>
        <%= text_field_tag "lname2", nil, "hint" => "Last name", :class => "input", :style => "width: 175px;" %>
        <%= text_field_tag "email2", nil, "hint" => "E-mail address", :class => "input", :style => "width: 175px;" %>
      </div>
      <div class="xfields">
        <%= text_field_tag "fname3", nil, "hint" => "First name", :class => "input", :style => "width: 175px;" %>
        <%= text_field_tag "lname3", nil, "hint" => "Last name", :class => "input", :style => "width: 175px;" %>
        <%= text_field_tag "email3", nil, "hint" => "E-mail address", :class => "input", :style => "width: 175px;" %>
      </div>
      <div class="xfields">
        <%= text_field_tag "fname4", nil, "hint" => "First name", :class => "input", :style => "width: 175px;" %>
        <%= text_field_tag "lname4", nil, "hint" => "Last name", :class => "input", :style => "width: 175px;" %>
        <%= text_field_tag "email4", nil, "hint" => "E-mail address", :class => "input", :style => "width: 175px;" %>
      </div>
      <div class="xfields">
        <%= text_field_tag "fname5", nil, "hint" => "First name", :class => "input", :style => "width: 175px;" %>
        <%= text_field_tag "lname5", nil, "hint" => "Last name", :class => "input", :style => "width: 175px;" %>
        <%= text_field_tag "email5", nil, "hint" => "E-mail address", :class => "input", :style => "width: 175px;" %>
      </div>
      <div class="xfields">
        <%= text_field_tag "fname6", nil, "hint" => "First name", :class => "input", :style => "width: 175px;" %>
        <%= text_field_tag "lname6", nil, "hint" => "Last name", :class => "input", :style => "width: 175px;" %>
        <%= text_field_tag "email6", nil, "hint" => "E-mail address", :class => "input", :style => "width: 175px;" %>
      </div>
      <div class="xfields">
        <%= text_field_tag "fname7", nil, "hint" => "First name", :class => "input", :style => "width: 175px;" %>
        <%= text_field_tag "lname7", nil, "hint" => "Last name", :class => "input", :style => "width: 175px;" %>
        <%= text_field_tag "email7", nil, "hint" => "E-mail address", :class => "input", :style => "width: 175px;" %>
      </div>
      <div class="xfields">
        <%= text_field_tag "fname8", nil, "hint" => "First name", :class => "input", :style => "width: 175px;" %>
        <%= text_field_tag "lname8", nil, "hint" => "Last name", :class => "input", :style => "width: 175px;" %>
        <%= text_field_tag "email8", nil, "hint" => "E-mail address", :class => "input", :style => "width: 175px;" %>
      </div>
      <div class="xfields">
        <%= text_field_tag "fname9", nil, "hint" => "First name", :class => "input", :style => "width: 175px;" %>
        <%= text_field_tag "lname9", nil, "hint" => "Last name", :class => "input", :style => "width: 175px;" %>
        <%= text_field_tag "email9", nil, "hint" => "E-mail address", :class => "input", :style => "width: 175px;" %>
      </div>
      <div class="xfields">
        <%= text_field_tag "fname10", nil, "hint" => "First name", :class => "input", :style => "width: 175px;" %>
        <%= text_field_tag "lname10", nil, "hint" => "Last name", :class => "input", :style => "width: 175px;" %>
        <%= text_field_tag "email10", nil, "hint" => "E-mail address", :class => "input", :style => "width: 175px;" %>
      </div>
      <div class="xfields" style="margin-top: 10px;">
        <%= text_area_tag "message", nil, "hint" => "You can add a message telling your friends how Pop Up Storz is great for finding or renting spaces...", :class => "input", :size => "250x6", :style => "width:63%; font-size: 1em;" %>
      </div>

      <div class="xfields" style="margin-top: 20px;">
        <div style="float: left;margin-top: 5px;clear:both;">
          <%= submit_tag "Send Invitation", :class=> "search", :style => "font-size: 16px; padding: 3px 10px;" %>
        </div>
      </div>

    </span>
    <%#*<div style="float: left;margin-top: 5px;clear:both;">%>
      <%#= submit_tag "Send Invitation" %>&nbsp;&nbsp;&nbsp;
    <%#*</div>%>
  <% end %>
</div>

app/views/admin/users/send_invitation.html.erb
<br/>
<p>
  <%= t(:send_invitation_to_users) %>
</p>
<select id="user_select">
  <option value=""> <%= t(:select_user) %></option>
  <%@users.each do |user| %>
    <%unless user==current_user%>
      <option value="<%=user.email%> "><%= user.email %></option>
    <%end%>
  <%end%>
</select>
<div style="margin-top: 20px;">
  <%=form_tag send_invitation_to_users_admin_users_path do |f|%>
    <%=text_field_tag "user[]"%><br/>
    <%= submit_tag t(:send) %>
  <%end%>
</div>

<script type="text/javascript">
  var s = "";
  $("#user_select").change(function() {
  
  var $option = $(this).val();
  s +=  ", " + $option + "\n";
  <%#*var selectedValue = $(this).val();%>
  $('#user_').val(s);
  var index = $('#user_select').get(0).selectedIndex;
  $('#user_select option:eq(' + index + ')').remove();
  });
</script>