config/routes.rb
# -*- encoding : utf-8 -*-
PopupStorz::Application.routes.draw do
  get "users/show"

  match "/users/update" => "users#update"
  match '/auth/:provider/callback' => 'services#create'
  match '/auth/facebook/callback' => 'services#create'
  match '/auth/twitter/callback' => 'services#create'
  match '/items/search_keyword' => 'items#search_keyword'
  match '/items/search_category/:id' => 'items#search_category'
  match '/notifications/destroy/:id' => 'notifications#destroy'
  match '/members' => 'users#members'
  match '/admin_items' => "admin/items#index"
  match '/admin_gatherings' => "admin/offers#gatherings"
  match '/admin/users/create' => "admin/users#create"
  match '/admin_send_invitations' => "admin/users#send_invitations"
  #  match '/search_members' => 'users#search_members'
  match '/search_gatherings' => 'searches#search_gatherings'
  match '/search_spaces' => 'searches#search_spaces'
  match '/admin_destroy_user/:id' => "admin/users#destroy_user"
  match '/admin_edit_user/:id' => "admin/users#edit"
  match '/admin_users' => "admin/users#index"
  match '/delete_listings' => "admin/items#delete_listings"
  match "/search_via_price_range" => "items#search_via_price_range"
  match "/items/new/:id" => "items#new_comment"
  match "/items/add_comment" => "items#add_comment"
  match "/items/show/:id" => "items#show"
  match "/users/add_comment" => "users#add_comment"
  match "/items/pop_ups" => "items#my_pop_ups"
  match "/home/terms" => "home#terms"
  match "/home/contact" => "home#contact"
  match "/home/feedback" => "home#feedback"
  match "/home/send_feedback" => "home#send_feedback"
  match "/email_settings" => "email_settings#index"
  
  match "/items/payment_charge/:id" => "items#payment_charge"
  match "/home/pay" => "home#pay"
  match "/join_gathering/:id" => "offers#join_gathering"
  match "/join/:id" => "offers#join"
  match "/approve_gathering_request/:id" => "offers#approve_gathering_request"
  match "/decline_gathering_request/:id" => "offers#decline_gathering_request"
  match "/accept_gathering/:id" => "offers#accept"
  match "/reject_gathering/:id" => "offers#decline"
  match "/products/cancelled_payment_request" => "products#cancelled_payment_request", :as  => :cancel_request
  match "products/completed_payment_request" => "products#completed_payment_request", :as => :complete_request
  match "/send_invitation" => "users#send_invitation"
  match "/invitation" => "users#invitations"
  match "/users/callback" => "users#callback"
  match "/users/send_invitation_to_contacts" => "users#send_invitation_to_contacts"
  match "/contacts/failure" => "users#send_invitation_to_contacts"
  
  match "/email_settings/index" => "email_settings#index"
  match "/email_settings/show" => "email_settings#show"
  match "/email_settings/create" => "email_settings#create"
  match "/email_settings/edit" => "email_settings#edit"
  match "/email_settings/update/:id" => "email_settings#update"
  match "/users/deactivate_account" => "users#deactivate_account"
  match "/send_resposne_request" => "offers#send_resposne_request"
  match "/send_gathering_deadline/:id" => "offers#send_gathering_deadline"
  match "/update_gathering_deadline" => "offers#update_gathering_deadline"
  match "/pending_gathering_acceptance" => "offers#pending_gathering_acceptance"
  match "/offers/add_comment" => "offers#add_comment"
  match "/cancel_booking/:id" => "offers#cancel_booking"
  match "/searches/user_rating" => "searches#user_rating"
  
  devise_for :users, :controllers => {:registrations => "registrations"}

  resources :accounts do
    collection do
      get 'verification_selection'
    end
  end

  resources :searches do
    collection do
      get "search_home"
      get "gatherings"
      get "members"
      get "spaces"
      post "search_gatherings"
      post "search_members"
      post "search_spaces"
    end
  end
  
  resources :email_settings do    
  end

  match '/items/set_dates' => "items#set_dates", :as => :set_dates
  match '/items/exchange_price' => "items#exchange_price", :as => :exchange_price

  resources :ratings do
    collection do
      get "rate"
      post "rate"
    end
  end
  
  resources :messages do
    collection do
      get 'inbox'
      get 'compose'
      get 'sent_items'
      get 'trash'      
      get 'delete'
      get 'empty_trash'
      get 'reply'

      post 'do_reply'
      post 'manage'
      post 'send_message'
      post 'contact_me'
      post 'gathering_message'
    end
  end

  match "account/:id/dashboard" => "accounts#dashboard",  :as  => :dashboard
  match "accept_invitation/:id" => "invitations#accept_invitation",  :as  => :accept_invitation
  match '/sign_out' => 'devise/sessions#destroy'

  devise_for :users do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  get "home/index"
  get "home/about"
  get "items/new"
  
  namespace :admin do
    resources :items do
      collection do
        get :change_recommendation
        post :transfer_ownership
        post :change_commission_rate
        get :change_rate
        post :change_all
        post :display_on_home
        get :active_inactive
        get :offer_activation
      end      
    end
    resources :users do
      collection do
        get :delete_message
        get :all_messages
        post :all_messages
        get :all_feedbacks
        post :all_feedbacks
        get :all_ratings
        get :delete_rating
        get :delete_comment
        #        get :send_invitation
        get :invitations
        post :send_invitation_to_users
        post :send_invitations
        post :send_invitation
        get :all_payments
        get :cancel_payment
#        get :all_feedbacks        
      end
    end
    resources :offers do
      collection do
        post :change_commission_rate
        post :add_comment
      end
    end
    resources :messages do
      collection do
        get :send_to_all
        post :send_message_to_all
        post :send_message_to_user
        get :send_message
      end
    end
  end
  resources :services do
    get "/services/create/:id" => "services#create"
  end
  resources :invitations do
    collection do
      get :fetch
      post :fetch
      post :send_emails
    end
  end

  namespace :xml do
    match 'location_search.xml' => 'LocationSearch#index', :format => :xml
    match 'address_search.xml'  => 'AddressSearch#index' , :format => :xml
  end

  resources :ratings do
    collection do
      get "rate"
      post "rate"
    end
  end
  resources :offers
  resources :avatars
  resources :items do
    collection do
      get "overview"
      get "created_prev_gatherings"
      get "created_coming_gatherings"
      get "pending_gathering_acceptance"
      get "gatherings_at_my_place"
      get "listings_home"
      get "past_transactions"
      get "search_item_spaces"
    end
    resources :avatars
    collection do
      get "sent_requests"      
    end
    get :autocomplete_item_title, :on => :collection
    get :autocomplete_item_city, :on => :collection
    get :add_to_favorite, :on => :member
    get :remove_from_favorite, :on => :member
    get :remove_from_favorite_on, :on => :member
    get :favorites, :on => :collection
    resources :offers do
      resources :payments
      member do
        get 'decline'
        get 'accept'
      end
    end
  end
  
  match '/users/:id/profile' => 'users#show', :as => :profile
  match '/users/:id/profile/edit' => 'users#edit', :as => :edit_profile
  match 'admin/users/:id/profile' => 'admin/users#show', :as => :admin_profile
  root :to => "home#index"
end

app/models/account.rb
# -*- encoding : utf-8 -*-
class Account < ActiveRecord::Base
  belongs_to :user
end

app/controllers/accounts_controller.rb
# -*- encoding : utf-8 -*-
class AccountsController < ApplicationController

  def dashboard
    @notifications = current_user.notifications
    @notifications.update_all(:is_read => true)
  end

  def new
    @account = Account.find_by_user_id(current_user.id)
  end

  def verification_selection
    respond_to do |format|
      format.js do
        @account = Account.find_by_id(params[:account_id])
        render_page_according_to_verification_type(params[:verification_type])
      end
    end
  end

  def update
    @account = Account.find_by_id(params[:id])
    case params[:verification_type]
    when "cc"
      do_cc_verification
    end
    redirect_to new_account_path
  end

  def render_page_according_to_verification_type(verification_type)
    case verification_type
    when "sms"
      if @account.is_sms_verified
        foo = ("<h2>#{t(:verified_sms)}</h2>").to_json
      else
        foo = render_to_string(:partial => '/accounts/sms_verify', :locals => { :account => @account }).to_json
      end
      render :js => "$('#verification_div').html(#{foo})"
    when "picture"
      if @account.is_picture_verified
        foo = ("<h2>#{t(:verified_picture)}</h2>").to_json
      else
        foo = render_to_string(:partial => '/accounts/picture_verify', :locals => { :account => @account }).to_json
      end
      render :js => "$('#verification_div').html(#{foo})"
    when "cc"
      if @account.is_cc_verified
        foo = ("<h2>#{t(:verified_card)}</h2>").to_json
      else
        foo = render_to_string(:partial => '/accounts/credit_card_verify', :locals => { :account => @account }).to_json
      end
      render :js => "$('#verification_div').html(#{foo})"
    when "facebook"
      if @account.is_facebook_verified
        foo = ("<h2>#{t(:verified_facebook)}</h2>").to_json
      else
        foo = render_to_string(:partial => '/accounts/facebook_verify', :locals => { :account => @account }).to_json
      end
      render :js => "$('#verification_div').html(#{foo})"
    when "linkedin"
      if @account.is_linkedin_verified
        foo = ("<h2>#{t(:verified_linkedin)}</h2>").to_json
      else
        foo = render_to_string(:partial => '/accounts/linkedin_verify', :locals => { :account => @account }).to_json
      end
      render :js => "$('#verification_div').html(#{foo})"
    when "twitter"
      if @account.is_twitter_verified
        foo = ("<h2>#{t(:verified_twitter)}</h2>").to_json
      else
        foo = render_to_string(:partial => '/accounts/twitter_verify', :locals => { :account => @account }).to_json
      end
      render :js => "$('#verification_div').html(#{foo})"
    end
  end

  def do_cc_verification
    unless params[:account][:stripe_card_token].blank?
      @account.update_attribute("stripe_card_token",params[:account][:stripe_card_token])
      @account.update_attribute("is_cc_verified",true)
      flash[:notice] = t(:card_verified)
    end
  end
  
end

app/helpers/accounts_helper.rb
# -*- encoding : utf-8 -*-
module AccountsHelper
  
  def number_to_currency(number, options = {})
    options[:locale] ||= I18n.locale
    super(number, options)
  end
  
end

app/views/accounts/_credit_card_verify.html.erb
<script type="text/javascript">
  $(function() {
    var subscription;

    jQuery(function() {
      Stripe.setPublishableKey($('meta[name="stripe-key"]').attr('content'));
      return subscription.setupForm();
    });

    subscription = {
      setupForm: function() {
        return $('#cc_verification_form').submit(function() {
          $('input[type=submit]').attr('disabled', true);
          subscription.processCard();
          return false;
        });
      },
      processCard: function() {
        var card;
        card = {
          number: $('#card_number').val(),
          cvc: $('#card_code').val(),
          expMonth: $('#card_month').val(),
          expYear: $('#card_year').val()
        };
        return Stripe.createToken(card, subscription.handleStripeResponse);
      },
      handleStripeResponse: function(status, response) {
        if (status === 200) {
          $('#account_stripe_card_token').val(response.id);
          return $('#cc_verification_form')[0].submit();
        } else {
          $('#stripe_error').text(response.error.message);
          return $('input[type=submit]').attr('disabled', false);
        }
      }
    };

  }).call(this);
</script>

<h2>
  <%= t(:cc_verification) %>
</h2>
<div style="width: auto;height: auto;border: 1px solid silver;padding: 5px;">
  <p>
    <%= t(:cc_info_security_measure) %>
  </p>
</div>

<%= form_for @account, :html => {:id => "cc_verification_form"} do |f| %>
  <%= hidden_field_tag "verification_type", params[:verification_type] %>  
  <%= f.hidden_field :stripe_card_token %>
  <br/>
  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>
  <br/>
  <div class="field">
    <%= label_tag :card_number, "Credit Card Number " %>
    <%= text_field_tag :card_number, nil, name: nil %>
  </div>
  <br/>
  <div class="field">
    <%= label_tag :card_code, "Security Code on Card (CVV)" %>
    <%= text_field_tag :card_code, nil, name: nil %>
  </div>
  <br/>
  <div class="field">
    <%= label_tag :card_month, "Card Expiration" %>
    <%= select_month nil, {add_month_numbers_true: true}, {name: nil, id: "card_month"}%>
    <%= select_year nil, {start_year: Date.today.year, end_year: Date.today.year+15}, {name: nil, id: "card_year"}%>
  </div>
  <br/>
  <div id="stripe_error" style="padding: 5px;width :100%;float:left;font-style: italic;color: red;">
    <noscript>
      <%= t(:js_enabled) %>
    </noscript>
  </div>
  <br/>
  <div class="actions">
    <%= f.submit "Verify" %>
  </div>
<% end %>

app/views/accounts/_facebook_verify.html.erb
<%#
# To change this template, choose Tools | Templates
# and open the template in the editor.
%>

<%#= "_face_book_verify.html" %>

<div id="remote">
  <div id="services" class="box">
    <a href="/auth/facebook" class="services">
      <%= image_tag "facebook_64.png", :size => "194x25", :alt => "Facebook" %>
    </a>
  </div>
</div>

app/views/accounts/_notifications.html.erb
<% @notifications.each do |notification| %>
  <div style="float: left;margin: 5px;padding: 3px;border: 1px solid silver;background-color: #cccccc;width: 98%;">
    <%= raw(notification.description) %>
  <%#= link_to 'delete', "/notifications/destroy" %>
    <%= link_to 'x', "/notifications/destroy/#{notification.id}",
      :method => :delete, :remote => true %>
  </div>
<% end %>

app/views/accounts/_picture_verify.html.erb
<h2>
  <%= t(:picture_verification) %>
</h2>
<div style="width: auto;height: auto;border: 1px solid silver;padding: 5px;">
  <%= t(:picture_to_verify_you_exist) %>
</div>
<% unless @account.is_picture_verified %>
  <%= form_for @account, :html => {:multipart => true, :onsubmit => "if($('#photo').val() == ''){alert(#{t(:choose_file)});return false;}else{return true;}"} do |f| %>
    <br/>
    <%= hidden_field_tag "verification_type", params[:verification_type] %>
    <b> <%= t(:upload_picture) %></b><br/>
    <div class="newPaperclipFiles">
      <%= file_field_tag :photo %>
    </div>
    <br/><br/>
    <div class="actions">
      <%= submit_tag "Upload Picture" %>
    </div>
  <% end %>
<% end %>

app/views/accounts/_sms_verify.html.erb
<h2>
  <%= t(:sms_verification) %>
</h2>
<div style="width: auto;height: auto;border: 1px solid silver;padding: 5px;">
<%= t(mobile_num_to_verify_you_exits) %>
</div>
<% if @account.sms_verification_code.blank? %>
  <%= form_for @account, :remote => true do |f| %>
    <br/>
    <%= hidden_field_tag "verification_type", params[:verification_type] %>
    <b><%= t(:enter_number) %></b><br/>
    <%= text_field_tag "mobile_number", current_user.cell_phone.blank? ? "+30" : current_user.cell_phone  %>
    <br/><br/>
    <div class="actions">
      <%= f.submit "Send me Verification Code" %>
    </div>
  <% end %>
<% else %>
  <%= form_for @account, :remote => true do |f| %>
    <br/>
    <br/>
    <%= hidden_field_tag "verification_type", params[:verification_type] %>
    <%= text_field_tag "sms_verification_code" , "", :placeholder => "Enter Verification Code" %>
    <br/><br/>
    <div class="actions">
      <%= f.submit "Enter code and Submit" %>
    </div>
  <% end %>
<% end %>

app/views/accounts/_twitter_verify.html.erb
<%#
# To change this template, choose Tools | Templates
# and open the template in the editor.
%>

<%#= "_twitter_verify.html" %>
<div id="remote">
  <div id="services" class="box">
    <a href="/auth/twitter" class="services"><%= image_tag "twitter.png", :size => "194x25", :alt => "Twitter" %>        </a>
  </div>
</div>

app/views/accounts/dashboard.html.erb
<div id="right-dash" >
  <h1><%= t(:notification) %></h1>
</div>
<div style="float: left;width: 100%;border: 1px solid black;padding: 5px;">
  <h2>
    <span style="float: left;padding: 5px;background-color: <%= (params[:action] == 'index' or params[:action] == 'index') ? 'silver' : '' %>">
      <%= link_to 'Inbox', inbox_messages_path, :class => ((params[:controller] == "messages" and ( params[:action] == "inbox" or params[:action] == "index" )) ? "m_act" : "") %>
    </span>
    <span style="float: left;padding: 5px">
      &nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;
    </span>
    <span style="float: left;padding: 5px;background-color: <%= (params[:action] == 'overview' or params[:action] == 'overview') ? 'silver' : '' %>">
      <%= link_to 'Notifications', dashboard_path(current_user.id), :class => ((params[:controller] == "accounts" and ( params[:action] == "dashboard" )) ? "m_act" : "") %>
    </span>
  </h2>
</div>

<div style="float:left;width: 100%;" id="notifications_div">
  <%= render :partial => "notifications", :locals => {:notifications => @notifications} %>
</div>

app/views/accounts/new.html.erb
<div style="float: left;width: 250px;border: 1px solid silver;height: auto;padding: 5px;">
  <h2><%= t(:get_verified)%></h2>
  <%= link_to t(:verify_phone), verification_selection_accounts_path(:verification_type => "sms", :account_id => @account.id ), :remote => true %>&nbsp;<%= image_tag "#{@account.is_sms_verified ? 'true.gif' : 'false.gif'}" %><br/><br/>
  <%= link_to t(:verify_picture), verification_selection_accounts_path(:verification_type => "picture", :account_id => @account.id ), :remote => true %>&nbsp;<%= image_tag "#{@account.is_picture_verified ? 'true.gif' : 'false.gif'}" %><br/><br/>
<%#= link_to "Verify your Credit Card", verification_selection_accounts_path(:verification_type => "cc", :account_id => @account.id ), :remote => true %>
<%#= image_tag "#{@account.is_cc_verified ? 'true.gif' : 'false.gif'}" %>
  <%= link_to t(:verify_facebook), verification_selection_accounts_path(:verification_type => "facebook", :account_id => @account.id ), :remote => true %>&nbsp;<%= image_tag "#{@account.is_facebook_verified ? 'true.gif' : 'false.gif'}" %><br/><br/>
  <%= link_to t(:verify_twitter), verification_selection_accounts_path(:verification_type => "twitter", :account_id => @account.id ), :remote => true %>&nbsp;<%= image_tag "#{@account.is_twitter_verified ? 'true.gif' : 'false.gif'}" %><br/><br/>
<%#= link_to "LinkedIn Verification", verification_selection_accounts_path(:verification_type => "linkedin", :account_id => @account.id ), :remote => true %>&nbsp;
<%#= image_tag "#{@account.is_linkedin_verified ? 'true.gif' : 'false.gif'}" %>
</div>
<div id="verification_div" style="float: left;width: 500px;padding: 10px;">
  <%= t(:options_verify)%>
</div>
<div style="float: left;width: 400px;border: 1px solid silver;height: auto;padding: 10px;">
  <p>
    <%= t(:popupstorz_intro)%>
  </p>
  <p>
    <%= t(:popupstorz_intro2)%>
  </p>
</div>